CREATE TABLE "MEMBER" (
    "MEMBER_ID"     VARCHAR2(30)                            NOT NULL,
    "PASSWORD"      VARCHAR2(30)                            NOT NULL,
    "MEMBER_NAME"   VARCHAR2(15)                            NOT NULL,
    "BIRTH"         VARCHAR2(8)                             NULL,
    "MEM_PHONE"     VARCHAR2(13)                            NULL,
    "MEM_EMAIL"     VARCHAR2(20)                            NULL,
    "MEM_SSN"       VARCHAR2(14)                            NULL,
    "MKT_AGREE_YN"  VARCHAR2(1)         DEFAULT Y           NOT NULL,
    "BNFTS_MEDIA"   VARCHAR2(10)                            NULL,
    "MANAGER_YN"    VARCHAR2(1)         DEFAULT N           NOT NULL,
    "JOIN_DTTM"     DATE                DEFAULT SYSDATE     NOT NULL
);

COMMENT ON TABLE  "MEMBER"                IS '회원';
COMMENT ON COLUMN "MEMBER"."MEMBER_ID"    IS '멤버아이디';
COMMENT ON COLUMN "MEMBER"."PASSWORD"     IS '비밀번호';
COMMENT ON COLUMN "MEMBER"."MEMBER_NAME"  IS '이름';
COMMENT ON COLUMN "MEMBER"."BIRTH"        IS '생년월일';
COMMENT ON COLUMN "MEMBER"."MEM_PHONE"    IS '핸드폰번호';
COMMENT ON COLUMN "MEMBER"."MEM_EMAIL"    IS '이메일주소';
COMMENT ON COLUMN "MEMBER"."MEM_SSN"      IS '주민등록번호';
COMMENT ON COLUMN "MEMBER"."MKT_AGREE_YN" IS '마케팅동의여부';
COMMENT ON COLUMN "MEMBER"."BNFTS_MEDIA"  IS '혜택수신매체';
COMMENT ON COLUMN "MEMBER"."MANAGER_YN"   IS '관리자여부';
COMMENT ON COLUMN "MEMBER"."JOIN_DTTM"    IS '가입일시';

CREATE TABLE "MOVIE" (
    "MOVIE_NO"      VARCHAR2(10)        NOT NULL,
    "MV_KOR_NAME"   VARCHAR2(60)        NOT NULL,
    "MV_ENG_NAME"   VARCHAR2(50)        NULL,
    "MV_POSTER"     VARCHAR2(200)       NOT NULL,
    "MV_INTRO_CONT" VARCHAR2(500)       NULL,
    "MV_TYPE"       VARCHAR2(200)       NULL,
    "MV_DIRECTOR"   VARCHAR2(30)        NULL,
    "MV_GENRE"      VARCHAR2(50)        NULL,
    "MV_GRADE"      VARCHAR2(21)        NULL,
    "MV_OPEN_DATE"  VARCHAR2(10)        NULL,
    "MV_CASTINGS"   VARCHAR2(200)       NULL
);

COMMENT ON TABLE  "MOVIE"                 IS '영화';
COMMENT ON COLUMN "MOVIE"."MOVIE_NO"      IS '영화번호';
COMMENT ON COLUMN "MOVIE"."MV_KOR_NAME"   IS '영화한글명';
COMMENT ON COLUMN "MOVIE"."MV_ENG_NAME"   IS '영화영문명';
COMMENT ON COLUMN "MOVIE"."MV_POSTER"     IS '영화포스터이미지';
COMMENT ON COLUMN "MOVIE"."MV_INTRO_CONT" IS '영화한줄소개';
COMMENT ON COLUMN "MOVIE"."MV_TYPE"       IS '영화타입';
COMMENT ON COLUMN "MOVIE"."MV_DIRECTOR"   IS '영화감독';
COMMENT ON COLUMN "MOVIE"."MV_GENRE"      IS '장르';
COMMENT ON COLUMN "MOVIE"."MV_GRADE"      IS '등급(시청연령)';
COMMENT ON COLUMN "MOVIE"."MV_OPEN_DATE"  IS '영화개봉일';
COMMENT ON COLUMN "MOVIE"."MV_CASTINGS"   IS '출연진';

CREATE TABLE "MOVIE_VIDEO" (
    "VIDEO_NO"      VARCHAR2(20)        NOT NULL,
    "MOVIE_NO"      VARCHAR2(10)        NOT NULL,
    "VIDEO_TITLE"   VARCHAR2(30)        NOT NULL,
    "VIDEO_THUMB"   VARCHAR2(40)        NULL,
    "VIDEO_PATH"    VARCHAR2(40)        NOT NULL
);

COMMENT ON TABLE  "MOVIE_VIDEO"               IS '영화동영상';
COMMENT ON COLUMN "MOVIE_VIDEO"."VIDEO_NO"    IS '동영상번호';
COMMENT ON COLUMN "MOVIE_VIDEO"."MOVIE_NO"    IS '영화번호';
COMMENT ON COLUMN "MOVIE_VIDEO"."VIDEO_TITLE" IS '동영상제목';
COMMENT ON COLUMN "MOVIE_VIDEO"."VIDEO_THUMB" IS '동영상썸네일';
COMMENT ON COLUMN "MOVIE_VIDEO"."VIDEO_PATH"  IS '동영상경로';

CREATE TABLE "MOVIE_STEAL" (
    "MV_STEAL_NO"   VARCHAR2(20)        NOT NULL,
    "MOVIE_NO"      VARCHAR2(10)        NOT NULL,
    "MV_STEAL_NAME" VARCHAR2(20)        NOT NULL,
    "MV_STEAL_PATH" VARCHAR2(40)        NOT NULL
);

COMMENT ON TABLE  "MOVIE_STEAL"                 IS '영화스틸컷';
COMMENT ON COLUMN "MOVIE_STEAL"."MV_STEAL_NO"   IS '스틸컷번호';
COMMENT ON COLUMN "MOVIE_STEAL"."MOVIE_NO"      IS '영화번호';
COMMENT ON COLUMN "MOVIE_STEAL"."MV_STEAL_NAME" IS '스틸컷이름';
COMMENT ON COLUMN "MOVIE_STEAL"."MV_STEAL_PATH" IS '스틸컷경로';

CREATE TABLE "TICKET" (
    "TICKET_NO"         VARCHAR2(20)                    NOT NULL,
    "MEMBER_ID2"        VARCHAR2(30)                    NOT NULL,
    "SCRN_NO"           VARCHAR2(20)                    NOT NULL,
    "TICKET_DV"         VARCHAR2(30)    DEFAULT ADULT   NOT NULL,
    "SEAT_NO"           VARCHAR2(20)                    NOT NULL,
    "TICKET_CNCL_DTTM"  DATE                            NULL
);

COMMENT ON TABLE  "TICKET"                    IS '예매';
COMMENT ON COLUMN "TICKET"."TICKET_NO"        IS '예매번호';
COMMENT ON COLUMN "TICKET"."MEMBER_ID2"       IS '멤버아이디';
COMMENT ON COLUMN "TICKET"."SCRN_NO"          IS '상영시간표번호';
COMMENT ON COLUMN "TICKET"."TICKET_DV"        IS '예매자구분(성인/ 장애인 / 우대 / 청소년)';
COMMENT ON COLUMN "TICKET"."SEAT_NO"          IS '좌석번호(ex) A열1번)';
COMMENT ON COLUMN "TICKET"."TICKET_CNCL_DTTM" IS '예매취소일시';

CREATE TABLE "CINEMA" (
    "CINEMA_ID"         VARCHAR2(10)        NOT NULL,
    "CINEMA_AREA"       VARCHAR2(40)        NOT NULL,
    "CINEMA_NAME"       VARCHAR2(40)        NOT NULL,
    "CINEMA_OPEN_DATE"  DATE                NULL
);

COMMENT ON TABLE  "CINEMA"                    IS '극장';
COMMENT ON COLUMN "CINEMA"."CINEMA_ID"        IS '극장아이디';
COMMENT ON COLUMN "CINEMA"."CINEMA_AREA"      IS '극장지역';
COMMENT ON COLUMN "CINEMA"."CINEMA_NAME"      IS '극장지점명';
COMMENT ON COLUMN "CINEMA"."CINEMA_OPEN_DATE" IS '극장개점일';

CREATE TABLE "THEATER" (
    "THEATER_NO"    VARCHAR2(10)                    NULL,
    "CINEMA_ID"     VARCHAR2(10)                    NOT NULL,
    "THEATER_NAME"  VARCHAR2(100)                   NULL,
    "SPECIAL_YN"    VARCHAR2(30)        DEFAULT N   NOT NULL,
    "VIDEO_QUALITY" VARCHAR2(4)                     NULL
);

COMMENT ON TABLE  "THEATER"                 IS '상영관';
COMMENT ON COLUMN "THEATER"."THEATER_NO"    IS '상영관번호';
COMMENT ON COLUMN "THEATER"."CINEMA_ID"     IS '극장아이디';
COMMENT ON COLUMN "THEATER"."THEATER_NAME"  IS '상영관이름';
COMMENT ON COLUMN "THEATER"."SPECIAL_YN"    IS '특별관여부';
COMMENT ON COLUMN "THEATER"."VIDEO_QUALITY" IS '상영화질';

CREATE TABLE "FAQ" (
    "FAQ_NO"        VARCHAR2(20)        NOT NULL,
    "FAQ_TITLE"     VARCHAR2(100)       NULL,
    "FAQ_CONTENT"   VARCHAR2(2000)      NULL,
    "FAQ_CATEGORY"  VARCHAR2(40)        NULL,
    "MEMBER_ID"     VARCHAR2(30)        NOT NULL
);

COMMENT ON TABLE  "FAQ"                IS '자주묻는질문';
COMMENT ON COLUMN "FAQ"."FAQ_NO"       IS '문의번호';
COMMENT ON COLUMN "FAQ"."FAQ_TITLE"    IS '문의제목';
COMMENT ON COLUMN "FAQ"."FAQ_CONTENT"  IS '문의내용';
COMMENT ON COLUMN "FAQ"."FAQ_CATEGORY" IS '문의필드';
COMMENT ON COLUMN "FAQ"."MEMBER_ID"    IS '멤버아이디';

CREATE TABLE "NOTICE" (
    "NOTICE_NO"         VARCHAR2(20)        NOT NULL,
    "NOTICE_TITLE"      VARCHAR2(200)       NOT NULL,
    "NOTICE_CONTENT"    VARCHAR2(3000)      NULL,
    "NOTICE_TYPE"       VARCHAR2(40)        NULL,
    "NOTICE_REG_DATE"   DATE                NOT NULL,
    "CINEMA_ID"         VARCHAR2(10)        NULL
);

COMMENT ON TABLE  "NOTICE"                   IS '공지사항';
COMMENT ON COLUMN "NOTICE"."NOTICE_NO"       IS '공지번호';
COMMENT ON COLUMN "NOTICE"."NOTICE_TITLE"    IS '공지제목';
COMMENT ON COLUMN "NOTICE"."NOTICE_CONTENT"  IS '공지내용';
COMMENT ON COLUMN "NOTICE"."NOTICE_TYPE"     IS '공지구분';
COMMENT ON COLUMN "NOTICE"."NOTICE_REG_DATE" IS '공지등록일';
COMMENT ON COLUMN "NOTICE"."CINEMA_ID"       IS '극장아이디';

CREATE TABLE "TIME_TABLE" (
    "SCRN_NO"       VARCHAR2(20)                          NOT NULL,
    "SCRN_STR_DTTM" DATE                                  NOT NULL,
    "MOVIE_NO"      VARCHAR2(100)                         NOT NULL,
    "THEATER_NO"    VARCHAR2(100)                         NULL,
    "SCRN_END_DTTM" DATE                                  NULL,
    "DISCOUNT_DV"   VARCHAR2(10)        DEFAULT 'DEFAULT' NULL
);

COMMENT ON TABLE  "TIME_TABLE"                 IS '상영시간표';
COMMENT ON COLUMN "TIME_TABLE"."SCRN_NO"       IS '상영시간표번호';
COMMENT ON COLUMN "TIME_TABLE"."SCRN_STR_DTTM" IS '상영시작일시';
COMMENT ON COLUMN "TIME_TABLE"."MOVIE_NO"      IS '영화번호';
COMMENT ON COLUMN "TIME_TABLE"."THEATER_NO"    IS '상영관번호';
COMMENT ON COLUMN "TIME_TABLE"."SCRN_END_DTTM" IS '상영종료일시';
COMMENT ON COLUMN "TIME_TABLE"."DISCOUNT_DV"   IS '할인구분(조조/심야)';

CREATE TABLE "MOVIE_EVAL" (
    "TICKET_NO"         VARCHAR2(20)                NOT NULL,
    "EVAL_POINT"        NUMBER(3)       DEFAULT 10  NOT NULL,
    "EVAL_COMMENT"      VARCHAR2(200)               NOT NULL,
    "EVAL_REG_DTTM"     DATE                        NOT NULL,
    "VIW_PNT_CONTENT"   VARCHAR2(50)                NOT NULL,
    "MOVIE_NO"          VARCHAR2(10)                NOT NULL
);

COMMENT ON TABLE  "MOVIE_EVAL"                   IS '영화평가';
COMMENT ON COLUMN "MOVIE_EVAL"."TICKET_NO"       IS '예매번호';
COMMENT ON COLUMN "MOVIE_EVAL"."EVAL_POINT"      IS '평가점수';
COMMENT ON COLUMN "MOVIE_EVAL"."EVAL_COMMENT"    IS '평가설명';
COMMENT ON COLUMN "MOVIE_EVAL"."EVAL_REG_DTTM"   IS '평가등록일';
COMMENT ON COLUMN "MOVIE_EVAL"."VIW_PNT_CONTENT" IS '관람포인트(연출  / 스토리 / 영상미 / 배우 / OST)';
COMMENT ON COLUMN "MOVIE_EVAL"."MOVIE_NO"        IS '영화번호';

CREATE TABLE "QUESTION" (
    "QUEST_NO"          VARCHAR2(200)       NOT NULL,
    "QUEST_TITLE"       VARCHAR2(200)       NOT NULL,
    "QUEST_CONTENT"     VARCHAR2(4000)      NULL,
    "QUEST_PASS_NO"     NUMBER(4)           NOT NULL,
    "QUEST_PHONE"       VARCHAR2(20)        NULL,
    "QUEST_NAME"        VARCHAR2(20)        NULL,
    "QUEST_DIVISION"    VARCHAR2(200)       NULL,
    "QUEST_EMAIL"       VARCHAR2(50)        NULL,
    "QUEST_TYPE"        VARCHAR2(20)        NULL,
    "PICTR_FILE"        VARCHAR2(200)       NULL,
    "VISIT_NUM"         NUMBER(5)           NULL,
    "RENTAL_DATE"       DATE                NULL,
    "RENTAL_TIME"       VARCHAR2(8)         NULL,
    "MEMBER_ID"         VARCHAR2(30)        NULL,
    "LOST_CINEMA_ID"    VARCHAR2(10)        NULL,
    "CINEMA_ID"         VARCHAR2(10)        NULL,
    "ANSW_CONTENT"      VARCHAR2(200)       NULL,
    "ANSW_REG_DTTM"     DATE                NULL,
    "ANSW_MEMBER_ID"    VARCHAR2(30)        NULL,
    "QUEST_MOVIE"       VARCHAR2(25)        NULL,
    "LOSTPLACE"         VARCHAR2(25)        NULL,
    "DEL_YN"            VARCHAR2(10)        NULL
);

COMMENT ON TABLE  "QUESTION"                   IS '문의';
COMMENT ON COLUMN "QUESTION"."QUEST_NO"        IS '문의번호';
COMMENT ON COLUMN "QUESTION"."QUEST_TITLE"     IS '문의제목';
COMMENT ON COLUMN "QUESTION"."QUEST_CONTENT"   IS '문의내용';
COMMENT ON COLUMN "QUESTION"."QUEST_PASS_NO"   IS '문의글비밀번호';
COMMENT ON COLUMN "QUESTION"."QUEST_PHONE"     IS '휴대전화번호';
COMMENT ON COLUMN "QUESTION"."QUEST_NAME"      IS '이름';
COMMENT ON COLUMN "QUESTION"."QUEST_DIVISION"  IS '문의구분(분실물 / 일대일 / 대관)';
COMMENT ON COLUMN "QUESTION"."QUEST_EMAIL"     IS '분실물문의용컬럼';
COMMENT ON COLUMN "QUESTION"."QUEST_TYPE"      IS '일대일문의용컬럼';
COMMENT ON COLUMN "QUESTION"."PICTR_FILE"      IS '일대일문의용컬럼';
COMMENT ON COLUMN "QUESTION"."VISIT_NUM"       IS '대관문의용컬럼';
COMMENT ON COLUMN "QUESTION"."RENTAL_DATE"     IS '대관일(대관문의용컬럼)';
COMMENT ON COLUMN "QUESTION"."RENTAL_TIME"     IS '대관시간(대관문의용)';
COMMENT ON COLUMN "QUESTION"."MEMBER_ID"       IS '등록아이디';
COMMENT ON COLUMN "QUESTION"."LOST_CINEMA_ID"  IS '극장아이디';
COMMENT ON COLUMN "QUESTION"."CINEMA_ID"       IS '극장아이디';
COMMENT ON COLUMN "QUESTION"."ANSW_CONTENT"    IS '답변내용';
COMMENT ON COLUMN "QUESTION"."ANSW_REG_DTTM"   IS '답변등록일시';
COMMENT ON COLUMN "QUESTION"."ANSW_MEMBER_ID"  IS '답변아이디';
COMMENT ON COLUMN "QUESTION"."QUEST_MOVIE"     IS '관람영화명';
COMMENT ON COLUMN "QUESTION"."LOSTPLACE"       IS '분실장소';
COMMENT ON COLUMN "QUESTION"."DEL_YN"          IS '삭제여부';

CREATE TABLE "MOVIE_POST" (
    "POST_NO"       VARCHAR2(20)        NOT NULL,
    "TICKET_NO"     VARCHAR2(20)        NOT NULL,
    "POST_CONTENT"  VARCHAR2(100)       NULL,
    "REG_DTTM"      DATE                NOT NULL,
    "MV_STEAL_NO"   VARCHAR2(20)        NOT NULL,
    "MEMBER_ID"     VARCHAR2(30)        NOT NULL,
    "MOVIE_NO"      VARCHAR2(10)        NOT NULL
);

COMMENT ON TABLE  "MOVIE_POST"                IS '영화포스트';
COMMENT ON COLUMN "MOVIE_POST"."POST_NO"      IS '포스트번호';
COMMENT ON COLUMN "MOVIE_POST"."TICKET_NO"    IS '예매번호';
COMMENT ON COLUMN "MOVIE_POST"."POST_CONTENT" IS '포스트내용';
COMMENT ON COLUMN "MOVIE_POST"."REG_DTTM"     IS '등록일시';
COMMENT ON COLUMN "MOVIE_POST"."MV_STEAL_NO"  IS '포스트이미지번호';
COMMENT ON COLUMN "MOVIE_POST"."MEMBER_ID"    IS '멤버아이디';
COMMENT ON COLUMN "MOVIE_POST"."MOVIE_NO"     IS '영화번호';

CREATE TABLE "LIKE_EVAL" (
    "BOARD_NO"  VARCHAR2(20)        NOT NULL,
    "MEMBER_ID" VARCHAR2(30)        NOT NULL
);

COMMENT ON TABLE  "LIKE_EVAL"             IS '좋아요평가';
COMMENT ON COLUMN "LIKE_EVAL"."BOARD_NO"  IS '게시물번호';
COMMENT ON COLUMN "LIKE_EVAL"."MEMBER_ID" IS '멤버아이디';


ALTER TABLE "MEMBER"      ADD CONSTRAINT "PK_MEMBER"                    PRIMARY KEY (     "MEMBER_ID"  );
ALTER TABLE "MOVIE"       ADD CONSTRAINT "PK_MOVIE"                     PRIMARY KEY (     "MOVIE_NO"   );
ALTER TABLE "MOVIE_VIDEO" ADD CONSTRAINT "PK_MOVIE_VIDEO"               PRIMARY KEY (     "VIDEO_NO"   ,     "MOVIE_NO" );
ALTER TABLE "MOVIE_STEAL" ADD CONSTRAINT "PK_MOVIE_STEAL"               PRIMARY KEY (     "MV_STEAL_NO",     "MOVIE_NO" );
ALTER TABLE "TICKET"      ADD CONSTRAINT "PK_TICKET"                    PRIMARY KEY (     "TICKET_NO"  ,     "MEMBER_ID2",     "SCRN_NO" );
ALTER TABLE "CINEMA"      ADD CONSTRAINT "PK_CINEMA"                    PRIMARY KEY (     "CINEMA_ID"  );
ALTER TABLE "THEATER"     ADD CONSTRAINT "PK_THEATER"                   PRIMARY KEY (     "THEATER_NO" );
ALTER TABLE "FAQ"         ADD CONSTRAINT "PK_FAQ"                       PRIMARY KEY (     "FAQ_NO"     );
ALTER TABLE "NOTICE"      ADD CONSTRAINT "PK_NOTICE"                    PRIMARY KEY (     "NOTICE_NO"  );
ALTER TABLE "TIME_TABLE"  ADD CONSTRAINT "PK_TIME_TABLE"                PRIMARY KEY (     "SCRN_NO"    ,     "SCRN_STR_DTTM",     "MOVIE_NO",     "THEATER_NO" );
ALTER TABLE "MOVIE_EVAL"  ADD CONSTRAINT "PK_MOVIE_EVAL"                PRIMARY KEY (     "TICKET_NO"  );
ALTER TABLE "QUESTION"    ADD CONSTRAINT "PK_QUESTION"                  PRIMARY KEY (     "QUEST_NO"   );
ALTER TABLE "MOVIE_POST"  ADD CONSTRAINT "PK_MOVIE_POST"                PRIMARY KEY (     "POST_NO"    ,     "TICKET_NO" );
ALTER TABLE "LIKE_EVAL"   ADD CONSTRAINT "PK_LIKE_EVAL"                 PRIMARY KEY (     "BOARD_NO"   )



-- PK로 사용할
-- 각 영역 시퀀스 번호 생성
-- 1) 영화: MV
CREATE SEQUENCE SEQ_MV_NO
MAXVALUE 9999;
-- 2) 예매: TK
CREATE SEQUENCE SEQ_TK_NO
MAXVALUE 9999;
-- 3) 극장: CN
CREATE SEQUENCE SEQ_CN_NO
MAXVALUE 9999;
-- 4) 문의: QT
CREATE SEQUENCE SEQ_QT_NO
MAXVALUE 9999;
-- 5) 멤버: MEM
CREATE SEQUENCE SEQ_MEM_NO
MAXVALUE 9999;

SELECT * FROM USER_SEQUENCES;
