
-- 사용자 계정 생성하는 구문
-- [표현법] CREATE USER 계정명 IDENTIFIED BY 비밀번호;
-- CREATE USER C##PAWPAW IDENTIFIED BY PAWPAW;

-- SELECT * FROM DBA_USERS
 -- WHERE USERNAME = 'C##PAWPAW';

-- 생성한 사용자 계정에게 최소한의 권한(데이터관리, 접속) 부여
-- GRANT RESOURCE, CONNECT TO C##PAWPAW;

-- 테이블이 저장되는 공간인 테이블스페이스 할당
--ALTER USER C##PAWPAW DEFAULT TABLESPACE SYSTEM QUOTA UNLIMITED ON SYSTEM;
-- COMMIT;


-- 112.156.11.186
-- 8087


CREATE TABLE "MEMBER" 
(
       "MEMBER_NO"           NUMBER                       NOT NULL,
       "MEMBER_NAME"         VARCHAR2(30 BYTE)                NULL,
       "MEMBER_ID"           VARCHAR2(30 BYTE)                NULL,
       "MEMBER_PW"           VARCHAR2(100 BYTE)               NULL,
       "MEMBER_ROLE"         VARCHAR2(15 BYTE) DEFAULT 'ROLE_USER',
       "MEMBER_PHONE"        VARCHAR2(20 BYTE)                NULL,
       "MEMBER_EMAIL"        VARCHAR2(50 BYTE)                NULL,
       "MEMBER_BIRTH"        NUMBER                           NULL,
       "MEMBER_PET_NAME"     VARCHAR2(30 BYTE)                NULL,
       "MEMBER_PET_TYPE"     VARCHAR2(30 BYTE)                NULL,
       "MEMBER_STATUS"       VARCHAR2(2 BYTE) DEFAULT 'Y',
       "MEMBER_ED"           DATE             DEFAULT SYSDATE     ,
       "MEMBER_MD"           DATE             DEFAULT SYSDATE     ,
       "MRKT_AGREE_YN"       VARCHAR2(2 BYTE) DEFAULT 'N',
       "RECV_AGREE_YN"       VARCHAR2(2 BYTE) DEFAULT 'N',
       "LOCA_AGREE_YN"       VARCHAR2(2 BYTE) DEFAULT 'N',
);
COMMENT ON TABLE  "MEMBER" IS '회원';
COMMENT ON COLUMN "MEMBER"."MEMBER_NO"       IS '회원번호';
COMMENT ON COLUMN "MEMBER"."MEMBER_ID"       IS '회원아이디';
COMMENT ON COLUMN "MEMBER"."MEMBER_PW"       IS '비밀번호';
COMMENT ON COLUMN "MEMBER"."MEMBER_ROLE"     IS '회원타입';
COMMENT ON COLUMN "MEMBER"."MEMBER_PHONE"    IS '핸드폰번호';
COMMENT ON COLUMN "MEMBER"."MEMBER_EMAIL"    IS '이메일';
COMMENT ON COLUMN "MEMBER"."MEMBER_BIRTH"    IS '생년월일';
COMMENT ON COLUMN "MEMBER"."MEMBER_PET_NAME" IS '반려동물이름';
COMMENT ON COLUMN "MEMBER"."MEMBER_PET_TYPE" IS '반려동물종류';
COMMENT ON COLUMN "MEMBER"."MEMBER_STATUS"   IS '회원상태';
COMMENT ON COLUMN "MEMBER"."MEMBER_ED"       IS '회원가입일';
COMMENT ON COLUMN "MEMBER"."MEMBER_MD"       IS '정보수정일';
COMMENT ON COLUMN "MEMBER"."MRKT_AGREE_YN"   IS '마케팅동의여부';
COMMENT ON COLUMN "MEMBER"."RECV_AGREE_YN"   IS '수신동의여부';
COMMENT ON COLUMN "MEMBER"."LOCA_AGREE_YN"   IS '위치동의여부';



CREATE TABLE "MEMBER_ACCS_LOG"
(
       "MEMBER_NO"           NUMBER                   NOT NULL,
       "ACCESS_ADDR"         VARCHAR2(20 BYTE)        NOT NULL,
       "ACCESS_DATE"         DATE     DEFAULT SYSDATE NOT NULL,
       "ACCESS_PATH"         VARCHAR2(300 BYTE)           NULL
)

COMMENT ON TABLE  "MEMBER_ACCS_LOG"                      IS '회원접속내역';
COMMENT ON COLUMN "MEMBER_ACCS_LOG"."MEMBER_NO"          IS '회원번호';
COMMENT ON COLUMN "MEMBER_ACCS_LOG"."ACCESS_ADDR"        IS '접속주소';
COMMENT ON COLUMN "MEMBER_ACCS_LOG"."ACCESS_DATE"        IS '접속일시';
COMMENT ON COLUMN "MEMBER_ACCS_LOG"."ACCESS_PATH"        IS '접속경로';




CREATE TABLE "COMMUNITY" 
(
       "COMMUNITY_NO"          NUMBER                  NOT NULL,
       "COMMUNITY_CATEGORY"    VARCHAR2(30 BYTE)           NULL,
       "COMMUNITY_TITLE"       VARCHAR2(300 BYTE)          NULL,
       "COMMUNITY_CONTENT"     VARCHAR2(4000 BYTE)         NULL,
       "COMMUNITY_ED"          DATE             DEFAULT SYSDATE,
       "COMMUNITY_STATUS"      VARCHAR2(2 BYTE) DEFAULT 'Y',
       "COMMUNITY_COUNT"       NUMBER           DEFAULT 0,
       "COMMUNITY_O_FILENAME"  VARCHAR2(100 BYTE)          NULL,
       "COMMUNITY_R_FILENAME"  VARCHAR2(100 BYTE)          NULL,
       "NOTICE_IMPORTANT_YN"   VARCHAR2(3 BYTE) DEFAULT 'N',
       "COMMUNITY_WRITER_NO"   NUMBER                      NULL,
);
COMMENT ON TABLE  "COMMUNITY"  IS '커뮤니티';
COMMENT ON COLUMN "COMMUNITY"."COMMUNITY_NO"         IS '커뮤니티번호';
COMMENT ON COLUMN "COMMUNITY"."COMMUNITY_CATEGORY"   IS '커뮤니티분류';
COMMENT ON COLUMN "COMMUNITY"."COMMUNITY_TITLE"      IS '커뮤니티제목';
COMMENT ON COLUMN "COMMUNITY"."COMMUNITY_CONTENT"    IS '커뮤니티내용';
COMMENT ON COLUMN "COMMUNITY"."COMMUNITY_ED"         IS '커뮤니티등록일';
COMMENT ON COLUMN "COMMUNITY"."COMMUNITY_STATUS"     IS '커뮤니티상태';
COMMENT ON COLUMN "COMMUNITY"."COMMUNITY_COUNT"      IS '조회수';
COMMENT ON COLUMN "COMMUNITY"."COMMUNITY_O_FILENAME" IS '첨부파일원래이름';
COMMENT ON COLUMN "COMMUNITY"."COMMUNITY_R_FILENAME" IS '첨부파일변경이름';

CREATE TABLE "STAY" 
(
       "STAY_CONTENTID"       NUMBER               NOT NULL,
       "STAY_ADDRESS"         VARCHAR2(100 BYTE)       NULL,
       "STAY_DETAIL_ADDRESS"  VARCHAR2(100 BYTE)       NULL,
       "STAY_TITLE"           VARCHAR2(100 BYTE)       NULL,
       "AREACODE"             NUMBER                   NULL,
       "STAY_CATEGORY1"       VARCHAR2(30 BYTE)        NULL,
       "STAY_CATEGORY2"       VARCHAR2(30 BYTE)        NULL,
       "STAY_CATEGORY3"       VARCHAR2(30 BYTE)        NULL,
       "STAY_CONTENTTYPEID"   NUMBER                   NULL,
       "STAY_CREATETIME"      DATE                     NULL,
       "STAY_MODIFYTIME"      DATE                     NULL,
       "STAY_IMAGE"           VARCHAR2(1000 BYTE)      NULL,
       "MAPX"                 VARCHAR2(20 BYTE)        NULL,
       "MAPY"                 VARCHAR2(20 BYTE)        NULL,
       "MAPLEVEL"             VARCHAR2(20 BYTE)        NULL,
       "STAY_TEL"             VARCHAR2(30 BYTE)        NULL,
       "SIGUNGUCODE"          NUMBER                   NULL,
       "HOMEPAGE"             VARCHAR2(1000 BYTE)      NULL,
       "FAVOR_RCMD_YN"        VARCHAR2(20 BYTE) DEFAULT 'N',
       "OVERVIEW"             CLOB                     NULL,
);
COMMENT ON TABLE  "STAY"                                IS '숙박';
COMMENT ON COLUMN "STAY"."STAY_CONTENTID"               IS '콘텐츠아이디';
COMMENT ON COLUMN "STAY"."STAY_ADDRESS"                 IS '숙박주소';
COMMENT ON COLUMN "STAY"."STAY_DETAIL_ADDRESS"          IS '숙박상세주소';
COMMENT ON COLUMN "STAY"."STAY_TITLE"                   IS '숙소명';
COMMENT ON COLUMN "STAY"."AREACODE"                     IS '지역코드';
COMMENT ON COLUMN "STAY"."STAY_CATEGORY1"               IS '숙박대분류';
COMMENT ON COLUMN "STAY"."STAY_CATEGORY2"               IS '숙박중분류';
COMMENT ON COLUMN "STAY"."STAY_CATEGORY3"               IS '숙박소분류';
COMMENT ON COLUMN "STAY"."STAY_CONTENTTYPEID"           IS '콘텐츠타입아이디';
COMMENT ON COLUMN "STAY"."STAY_CREATETIME"              IS '등록일';
COMMENT ON COLUMN "STAY"."STAY_MODIFYTIME"              IS '수정일';
COMMENT ON COLUMN "STAY"."STAY_IMAGE"                   IS '대표이미지';
COMMENT ON COLUMN "STAY"."MAPX"                         IS 'X좌표';
COMMENT ON COLUMN "STAY"."MAPY"                         IS 'Y좌표';
COMMENT ON COLUMN "STAY"."MAPLEVEL"                     IS '축척';
COMMENT ON COLUMN "STAY"."STAY_TEL"                     IS '숙박전화번호';
COMMENT ON COLUMN "STAY"."SIGUNGUCODE"                  IS '시군구코드';
COMMENT ON COLUMN "STAY"."HOMEPAGE"                     IS '홈페이지주소';
COMMENT ON COLUMN "STAY"."FAVOR_RCMD_YN"                IS '인기추천여부';
COMMENT ON COLUMN "STAY"."OVERVIEW"                     IS '소개설명';

CREATE TABLE "TRIP" 
(
       "TRIP_CONTENTID"      NUMBER               NOT NULL,
       "TRIP_ADDRESS"        VARCHAR2(100 BYTE)       NULL,
       "TRIP_TITLE"          VARCHAR2(100 BYTE)       NULL,
       "AREACODE"            NUMBER                   NULL,
       "TRIP_CATEGORY1"      VARCHAR2(30 BYTE)        NULL,
       "TRIP_CATEGORY2"      VARCHAR2(30 BYTE)        NULL,
       "TRIP_CATEGORY3"      VARCHAR2(30 BYTE)        NULL,
       "TRIP_CONTENTTYPEID"  NUMBER                   NULL,
       "TRIP_CREATETIME"     DATE                     NULL,
       "TRIP_MODIFYTIME"     DATE                     NULL,
       "TRIP_IMAGE"          VARCHAR2(1000 BYTE)      NULL,
       "MAPX"                VARCHAR2(20 BYTE)        NULL,
       "MAPY"                VARCHAR2(20 BYTE)        NULL,
       "MAPLEVEL"            VARCHAR2(20 BYTE)        NULL,
       "TRIP_TEL"            VARCHAR2(30 BYTE)        NULL,
       "SIGUNGUCODE"         NUMBER                   NULL,
       "TRIP_DETAIL_ADDRESS" VARCHAR2(100 BYTE)       NULL,
       "HOMEPAGE"            VARCHAR2(1000 BYTE)      NULL,
       "FAVOR_RCMD_YN"       VARCHAR2(20 BYTE) DEFAULT 'N',
       "OVERVIEW"            CLOB                     NULL,
);
COMMENT ON TABLE  "TRIP"                               IS '여행';
COMMENT ON COLUMN "TRIP"."TRIP_CONTENTID"              IS '콘텐츠아이디';
COMMENT ON COLUMN "TRIP"."TRIP_ADDRESS"                IS '여행지주소';
COMMENT ON COLUMN "TRIP"."TRIP_TITLE"                  IS '여행지명';
COMMENT ON COLUMN "TRIP"."AREACODE"                    IS '지역코드';
COMMENT ON COLUMN "TRIP"."TRIP_CATEGORY1"              IS '여행대분류';
COMMENT ON COLUMN "TRIP"."TRIP_CATEGORY2"              IS '여행중분류';
COMMENT ON COLUMN "TRIP"."TRIP_CATEGORY3"              IS '여행소분류';
COMMENT ON COLUMN "TRIP"."TRIP_CONTENTTYPEID"          IS '콘텐츠타입아이디';
COMMENT ON COLUMN "TRIP"."TRIP_CREATETIME"             IS '등록일';
COMMENT ON COLUMN "TRIP"."TRIP_MODIFYTIME"             IS '수정일';
COMMENT ON COLUMN "TRIP"."TRIP_IMAGE"                  IS '이미지';
COMMENT ON COLUMN "TRIP"."MAPX"                        IS 'X좌표';
COMMENT ON COLUMN "TRIP"."MAPY"                        IS 'Y좌표';
COMMENT ON COLUMN "TRIP"."MAPLEVEL"                    IS '축척';
COMMENT ON COLUMN "TRIP"."TRIP_TEL"                    IS '여행전화번호';
COMMENT ON COLUMN "TRIP"."SIGUNGUCODE"                 IS '시군구코드';
COMMENT ON COLUMN "TRIP"."TRIP_DETAIL_ADDRESS"         IS '여행지상세주소';
COMMENT ON COLUMN "TRIP"."HOMEPAGE"                    IS '홈페이지주소';
COMMENT ON COLUMN "TRIP"."FAVOR_RCMD_YN"               IS '인기추천여부';
COMMENT ON COLUMN "TRIP"."OVERVIEW"                    IS '소개설명';



CREATE TABLE "COMM"
(
       "COMM_CONTENTID"      NUMBER          NOT NULL,
       "COMM_ADDRESS"        VARCHAR2(100 BYTE)  NULL,
       "COMM_DETAIL_ADDRESS" VARCHAR2(100 BYTE)  NULL,
       "COMM_TITLE"          VARCHAR2(100 BYTE)  NULL,
       "AREACODE"            VARCHAR2(20 BYTE)   NULL,
       "COMM_CATEGORY1"      VARCHAR2(30 BYTE)   NULL,
       "COMM_CATEGORY2"      VARCHAR2(30 BYTE)   NULL,
       "COMM_CATEGORY3"      VARCHAR2(30 BYTE)   NULL,
       "COMM_CONTENTTYPEID"  VARCHAR2(10 BYTE)   NULL,
       "COMM_CREATETIME"     VARCHAR2(20 BYTE)   NULL,
       "COMM_MODIFYTIME"     VARCHAR2(20 BYTE)   NULL,
       "COMM_IMAGE"          VARCHAR2(1000 BYTE) NULL,
       "MAPX"                VARCHAR2(20 BYTE)   NULL,
       "MAPY"                VARCHAR2(20 BYTE)   NULL,
       "MAPLEVEL"            VARCHAR2(20 BYTE)   NULL,
       "COMM_TEL"            VARCHAR2(30 BYTE)   NULL,
       "SIGUNGUCODE"         VARCHAR2(20 BYTE)   NULL,
       "HOMEPAGE"            VARCHAR2(1000 BYTE) NULL,
       "OVERVIEW"            VARCHAR2(4000 BYTE) NULL,
)

COMMENT ON TABLE  "COMM"                                  IS '공통';
COMMENT ON COLUMN "COMM"."COMM_ADDRESS"                   IS '공통컨텐츠주소';
COMMENT ON COLUMN "COMM"."COMM_DETAIL_ADDRESS"            IS '공통컨텐츠상세주소';
COMMENT ON COLUMN "COMM"."COMM_TITLE"                     IS '공통컨텐츠명';
COMMENT ON COLUMN "COMM"."AREACODE"                       IS '지역코드';
COMMENT ON COLUMN "COMM"."COMM_CATEGORY1"                 IS '공통컨텐츠대분류';
COMMENT ON COLUMN "COMM"."COMM_CATEGORY2"                 IS '공통컨텐츠중분류';
COMMENT ON COLUMN "COMM"."COMM_CATEGORY3"                 IS '공통컨텐츠소분류';
COMMENT ON COLUMN "COMM"."COMM_CONTENTTYPEID"             IS '콘텐츠타입아이디';
COMMENT ON COLUMN "COMM"."COMM_CREATETIME"                IS '등록일';
COMMENT ON COLUMN "COMM"."COMM_MODIFYTIME"                IS '수정일';
COMMENT ON COLUMN "COMM"."COMM_IMAGE"                     IS '이미지';
COMMENT ON COLUMN "COMM"."MAPX"                           IS 'X좌표';
COMMENT ON COLUMN "COMM"."MAPY"                           IS 'Y좌표';
COMMENT ON COLUMN "COMM"."MAPLEVEL"                       IS '축척';
COMMENT ON COLUMN "COMM"."COMM_TEL"                       IS '공통컨텐츠전화번호';
COMMENT ON COLUMN "COMM"."SIGUNGUCODE"                    IS '시군구코드';
COMMENT ON COLUMN "COMM"."HOMEPAGE"                       IS '홈페이지주소';
COMMENT ON COLUMN "COMM"."OVERVIEW"                       IS '소개설명';



CREATE TABLE "PETINFO" 
(
       "PETINFO_CONTENTID"   NUMBER              NOT NULL,
       "TOUR_INFO"           VARCHAR2(1000 BYTE)     NULL,
       "ACMPY_TYPE_CD"       VARCHAR2(200 BYTE)      NULL,
       "RELA_POSES_FCLTY"    VARCHAR2(600 BYTE)      NULL,
       "RELA_FRNSH_PRDLST"   VARCHAR2(300 BYTE)      NULL,
       "RELA_PURC_PRDLST"    VARCHAR2(200 BYTE)      NULL,
       "RELA_RNTL_PRDLST"    VARCHAR2(200 BYTE)      NULL,
       "ACMPY_PSBL_CPAM"     VARCHAR2(1000 BYTE)     NULL,
       "ETC_ACMPY_INFO"      VARCHAR2(4000 BYTE)     NULL,
       "ACMPY_NEED_MTR"      VARCHAR2(1000 BYTE)     NULL,
);
COMMENT ON TABLE  "PETINFO"                              IS '반려동물동반정보';
COMMENT ON COLUMN "PETINFO"."PETINFO_CONTENTID"          IS '콘텐츠아이디';
COMMENT ON COLUMN "PETINFO"."TOUR_INFO"                  IS '반려견관광정보';
COMMENT ON COLUMN "PETINFO"."ACMPY_TYPE_CD"              IS '동반구분';
COMMENT ON COLUMN "PETINFO"."RELA_POSES_FCLTY"           IS '관련구비시설';
COMMENT ON COLUMN "PETINFO"."RELA_FRNSH_PRDLST"          IS '관련비치품목';
COMMENT ON COLUMN "PETINFO"."RELA_PURC_PRDLST"           IS '관련구매품목';
COMMENT ON COLUMN "PETINFO"."RELA_RNTL_PRDLST"           IS '관련렌탈품목';
COMMENT ON COLUMN "PETINFO"."ACMPY_PSBL_CPAM"            IS '동반가능동물';
COMMENT ON COLUMN "PETINFO"."ETC_ACMPY_INFO"             IS '기타동반정보';
COMMENT ON COLUMN "PETINFO"."ACMPY_NEED_MTR"             IS '동반시필요사항';

CREATE TABLE "AREA" (
    "AREA_CODE"     NUMBER        NOT NULL,
    "SIGUNGU_CODE"  NUMBER        NOT NULL,
    "AREA_NAME"     VARCHAR2(50)  NOT NULL
);
COMMENT ON TABLE  "AREA" IS '지역';
COMMENT ON COLUMN "AREA"."AREA_CODE"    IS '지역코드';
COMMENT ON COLUMN "AREA"."SIGUNGU_CODE" IS '시군구코드';
COMMENT ON COLUMN "AREA"."AREA_NAME"    IS '지역시군구명';



CREATE TABLE "WEATHER_AREA"
(
       "AREA_GRP_CODE"       VARCHAR2(50 BYTE)      NULL,
       "AREA_GRP_NAME"       VARCHAR2(50 BYTE)      NULL,
       "AREA_CODE"           VARCHAR2(50 BYTE)      NULL,
       "AREA_NAME"           VARCHAR2(50 BYTE)      NULL
)

COMMENT ON COLUMN "WEATHER_AREA"                       IS '날씨지역';
COMMENT ON COLUMN "WEATHER_AREA"."AREA_GRP_CODE"       IS '날씨그룹코드';
COMMENT ON COLUMN "WEATHER_AREA"."AREA_GRP_NAME"       IS '날씨그룹명';
COMMENT ON COLUMN "WEATHER_AREA"."AREA_CODE"           IS '날씨코드';
COMMENT ON COLUMN "WEATHER_AREA"."AREA_NAME"           IS '날씨명';


CREATE TABLE "WEATHER_LAND_AREA"
(
       "AREA_CODE"           VARCHAR2(300 BYTE)      NULL,
       "AREA_NAME"           VARCHAR2(300 BYTE)      NULL
)

COMMENT ON COLUMN "WEATHER_LAND_AREA"                  IS '날씨지역';
COMMENT ON COLUMN "WEATHER_LAND_AREA"."AREA_CODE"      IS '날씨코드';
COMMENT ON COLUMN "WEATHER_LAND_AREA"."AREA_NAME"      IS '날씨명';



CREATE TABLE "BIGCATEGORY" (
    "BIG_CATE_CODE" VARCHAR2(30)        NOT NULL,
    "BIG_CATE_NAME" VARCHAR2(30)        NULL
);
COMMENT ON TABLE  "BIGCATEGORY" IS '빅카테고리';
COMMENT ON COLUMN "BIGCATEGORY"."BIG_CATE_CODE" IS '카테고리코드';
COMMENT ON COLUMN "BIGCATEGORY"."BIG_CATE_NAME" IS '카테고리이름';

CREATE TABLE "MIDCATEGORY" (
    "MID_CATE_CODE" VARCHAR2(30)        NOT NULL,
    "MID_CATE_NAME" VARCHAR2(30)        NULL
);
COMMENT ON TABLE  "MIDCATEGORY" IS '미들카테고리';
COMMENT ON COLUMN "MIDCATEGORY"."MID_CATE_CODE" IS '카테고리코드';
COMMENT ON COLUMN "MIDCATEGORY"."MID_CATE_NAME" IS '카테고리이름';

CREATE TABLE "SMLCATEGORY" (
    "SML_CATE_CODE" VARCHAR2(30)        NOT NULL,
    "SML_CATE_NAME" VARCHAR2(30)        NULL
);
COMMENT ON TABLE  "SMLCATEGORY" IS '스몰카테고리';
COMMENT ON COLUMN "SMLCATEGORY"."SML_CATE_CODE" IS '카테고리코드';
COMMENT ON COLUMN "SMLCATEGORY"."SML_CATE_NAME" IS '카테고리이름';


CREATE TABLE "ZZIM"
(
       "CONTENTID"           NUMBER        NULL,
       "MEMBER_NO"           NUMBER        NULL
)

COMMENT ON TABLE  "ZZIM"                              IS '지역찜';
COMMENT ON COLUMN "ZZIM"."CONTENTID"                  IS '컨텐츠아이디';
COMMENT ON COLUMN "ZZIM"."MEMBER_NO"                  IS '회원번호';

ALTER TABLE "MEMBER"      ADD CONSTRAINT "PK_MEMBER"      PRIMARY KEY ( "MEMBER_NO"         );
ALTER TABLE "COMMUNITY"   ADD CONSTRAINT "PK_COMMUNITY"   PRIMARY KEY ( "COMMUNITY_NO"      );
ALTER TABLE "STAY"        ADD CONSTRAINT "PK_STAY"        PRIMARY KEY ( "STAY_CONTENTID"    );
ALTER TABLE "TRIP"        ADD CONSTRAINT "PK_TRIP"        PRIMARY KEY ( "TRIP_CONTENTID"    );
ALTER TABLE "PETINFO"     ADD CONSTRAINT "PK_PETINFO"     PRIMARY KEY ( "PETINFO_CONTENTID" );
ALTER TABLE "AREA"        ADD CONSTRAINT "PK_AREA"        PRIMARY KEY ( "AREA_CODE", "SIGUNGU_CODE" );
ALTER TABLE "BIGCATEGORY" ADD CONSTRAINT "PK_BIGCATEGORY" PRIMARY KEY ( "BIG_CATE_CODE"     );
ALTER TABLE "MIDCATEGORY" ADD CONSTRAINT "PK_MIDCATEGORY" PRIMARY KEY ( "MID_CATE_CODE"     );
ALTER TABLE "SMLCATEGORY" ADD CONSTRAINT "PK_SMLCATEGORY" PRIMARY KEY ( "SML_CATE_CODE"     );



--------------------------------------------------------------------------------------------------------------------------------------------------------
-- 회원 테이블
CREATE SEQUENCE SEQ_MEM_NO;

ALTER TABLE MEMBER MODIFY MEMBER_STATUS DEFAULT 'Y';
ALTER TABLE MEMBER MODIFY MEMBER_ED DEFAULT SYSDATE;
ALTER TABLE MEMBER MODIFY MEMBER_MD DEFAULT SYSDATE;

SELECT * FROM MEMBER;

-- 회원 추가
INSERT INTO MEMBER VALUES(SEQ_MEM_NO.NEXTVAL, 'lee0101', '1234', 'ROLE_USER', '01012345678', 'lee0101@naver.com', '20000101', '영길이', '시츄', 'Y', SYSDATE, SYSDATE, 'N', 'N', 'N');
INSERT INTO MEMBER VALUES(SEQ_MEM_NO.NEXTVAL, 'yang0202', '1234', 'ROLE_USER', '01078945612', 'yang0202@gmail.com', '20020311', '방맹이', '푸들', 'Y', SYSDATE, SYSDATE, 'N', 'N', 'N');
INSERT INTO MEMBER VALUES(SEQ_MEM_NO.NEXTVAL, 'kim0303', '1234', 'ROLE_USER', '01055552222', 'kim0303@daum.net', '19990621', '복실이', '프렌치 불도그', 'Y', SYSDATE, SYSDATE, 'N', 'N', 'N');
INSERT INTO MEMBER VALUES(SEQ_MEM_NO.NEXTVAL, 'song0404', '1234', 'ROLE_USER', '01098745632', 'song0404@nate.com', '19990228', '동강이', '말티즈', 'Y', SYSDATE, SYSDATE, 'N', 'N', 'N');

COMMIT;



INSERT INTO AREA VALUES(1, 0, '서울');
INSERT INTO AREA VALUES(1, 1, '강남구');
INSERT INTO AREA VALUES(1, 2, '강동구');
INSERT INTO AREA VALUES(1, 3, '강북구');
INSERT INTO AREA VALUES(1, 4, '강서구');
INSERT INTO AREA VALUES(1, 5, '관악구');
INSERT INTO AREA VALUES(1, 6, '광진구');
INSERT INTO AREA VALUES(1, 7, '구로구');
INSERT INTO AREA VALUES(1, 8, '금천구');
INSERT INTO AREA VALUES(1, 9, '노원구');
INSERT INTO AREA VALUES(1, 10, '도봉구');
INSERT INTO AREA VALUES(1, 11, '동대문구');
INSERT INTO AREA VALUES(1, 12, '동작구');
INSERT INTO AREA VALUES(1, 13, '마포구');
INSERT INTO AREA VALUES(1, 14, '서대문구');
INSERT INTO AREA VALUES(1, 15, '서초구');
INSERT INTO AREA VALUES(1, 16, '성동구');
INSERT INTO AREA VALUES(1, 17, '성북구');
INSERT INTO AREA VALUES(1, 18, '송파구');
INSERT INTO AREA VALUES(1, 19, '양천구');
INSERT INTO AREA VALUES(1, 20, '영등포구');
INSERT INTO AREA VALUES(1, 21, '용산구');
INSERT INTO AREA VALUES(1, 22, '은평구');
INSERT INTO AREA VALUES(1, 23, '종로구');
INSERT INTO AREA VALUES(1, 24, '중구');
INSERT INTO AREA VALUES(1, 25, '중랑구');
INSERT INTO AREA VALUES(2, 0, '인천');
INSERT INTO AREA VALUES(2, 1, '강화군');
INSERT INTO AREA VALUES(2, 2, '계양구');
INSERT INTO AREA VALUES(2, 3, '미추홀구');
INSERT INTO AREA VALUES(2, 4, '남동구');
INSERT INTO AREA VALUES(2, 5, '동구');
INSERT INTO AREA VALUES(2, 6, '부평구');
INSERT INTO AREA VALUES(2, 7, '서구');
INSERT INTO AREA VALUES(2, 8, '연수구');
INSERT INTO AREA VALUES(2, 9, '옹진군');
INSERT INTO AREA VALUES(2, 10, '중구');
INSERT INTO AREA VALUES(3, 0, '대전');
INSERT INTO AREA VALUES(3, 1, '대덕구');
INSERT INTO AREA VALUES(3, 2, '동구');
INSERT INTO AREA VALUES(3, 3, '서구');
INSERT INTO AREA VALUES(3, 4, '유성구');
INSERT INTO AREA VALUES(3, 5, '중구');
INSERT INTO AREA VALUES(4, 0, '대구');
INSERT INTO AREA VALUES(4, 1, '남구');
INSERT INTO AREA VALUES(4, 2, '달서구');
INSERT INTO AREA VALUES(4, 3, '달성군');
INSERT INTO AREA VALUES(4, 4, '동구');
INSERT INTO AREA VALUES(4, 5, '북구');
INSERT INTO AREA VALUES(4, 6, '서구');
INSERT INTO AREA VALUES(4, 7, '수성구');
INSERT INTO AREA VALUES(4, 8, '중구');
INSERT INTO AREA VALUES(4, 9, '군위군');
INSERT INTO AREA VALUES(5, 0, '광주');
INSERT INTO AREA VALUES(5, 1, '광산구');
INSERT INTO AREA VALUES(5, 2, '남구');
INSERT INTO AREA VALUES(5, 3, '동구');
INSERT INTO AREA VALUES(5, 4, '북구');
INSERT INTO AREA VALUES(5, 5, '서구');
INSERT INTO AREA VALUES(6, 0, '부산');
INSERT INTO AREA VALUES(6, 1, '강서구');
INSERT INTO AREA VALUES(6, 2, '금정구');
INSERT INTO AREA VALUES(6, 3, '기장군');
INSERT INTO AREA VALUES(6, 4, '남구');
INSERT INTO AREA VALUES(6, 5, '동구');
INSERT INTO AREA VALUES(6, 6, '동래구');
INSERT INTO AREA VALUES(6, 7, '부산진구');
INSERT INTO AREA VALUES(6, 8, '북구');
INSERT INTO AREA VALUES(6, 9, '사상구');
INSERT INTO AREA VALUES(6, 10, '사하구');
INSERT INTO AREA VALUES(6, 11, '서구');
INSERT INTO AREA VALUES(6, 12, '수영구');
INSERT INTO AREA VALUES(6, 13, '연제구');
INSERT INTO AREA VALUES(6, 14, '영도구');
INSERT INTO AREA VALUES(6, 15, '중구');
INSERT INTO AREA VALUES(6, 16, '해운대구');
INSERT INTO AREA VALUES(7, 0, '울산');
INSERT INTO AREA VALUES(7, 1, '중구');
INSERT INTO AREA VALUES(7, 2, '남구');
INSERT INTO AREA VALUES(7, 3, '동구');
INSERT INTO AREA VALUES(7, 4, '북구');
INSERT INTO AREA VALUES(7, 5, '울주군');
INSERT INTO AREA VALUES(8, 0, '세종특별자치시');
INSERT INTO AREA VALUES(8, 1, '세종특별자치시');
INSERT INTO AREA VALUES(31, 0, '경기도');
INSERT INTO AREA VALUES(31, 1, '가평군');
INSERT INTO AREA VALUES(31, 2, '고양시');
INSERT INTO AREA VALUES(31, 3, '과천시');
INSERT INTO AREA VALUES(31, 4, '광명시');
INSERT INTO AREA VALUES(31, 5, '광주시');
INSERT INTO AREA VALUES(31, 6, '구리시');
INSERT INTO AREA VALUES(31, 7, '군포시');
INSERT INTO AREA VALUES(31, 8, '김포시');
INSERT INTO AREA VALUES(31, 9, '남양주시');
INSERT INTO AREA VALUES(31, 10, '동두천시');
INSERT INTO AREA VALUES(31, 11, '부천시');
INSERT INTO AREA VALUES(31, 12, '성남시');
INSERT INTO AREA VALUES(31, 13, '수원시');
INSERT INTO AREA VALUES(31, 14, '시흥시');
INSERT INTO AREA VALUES(31, 15, '안산시');
INSERT INTO AREA VALUES(31, 16, '안성시');
INSERT INTO AREA VALUES(31, 17, '안양시');
INSERT INTO AREA VALUES(31, 18, '양주시');
INSERT INTO AREA VALUES(31, 19, '양평군');
INSERT INTO AREA VALUES(31, 20, '여주시');
INSERT INTO AREA VALUES(31, 21, '연천군');
INSERT INTO AREA VALUES(31, 22, '오산시');
INSERT INTO AREA VALUES(31, 23, '용인시');
INSERT INTO AREA VALUES(31, 24, '의왕시');
INSERT INTO AREA VALUES(31, 25, '의정부시');
INSERT INTO AREA VALUES(31, 26, '이천시');
INSERT INTO AREA VALUES(31, 27, '파주시');
INSERT INTO AREA VALUES(31, 28, '평택시');
INSERT INTO AREA VALUES(31, 29, '포천시');
INSERT INTO AREA VALUES(31, 30, '하남시');
INSERT INTO AREA VALUES(31, 31, '화성시');
INSERT INTO AREA VALUES(32, 0, '강원특별자치도');
INSERT INTO AREA VALUES(32, 1, '강릉시');
INSERT INTO AREA VALUES(32, 2, '고성군');
INSERT INTO AREA VALUES(32, 3, '동해시');
INSERT INTO AREA VALUES(32, 4, '삼척시');
INSERT INTO AREA VALUES(32, 5, '속초시');
INSERT INTO AREA VALUES(32, 6, '양구군');
INSERT INTO AREA VALUES(32, 7, '양양군');
INSERT INTO AREA VALUES(32, 8, '영월군');
INSERT INTO AREA VALUES(32, 9, '원주시');
INSERT INTO AREA VALUES(32, 10, '인제군');
INSERT INTO AREA VALUES(32, 11, '정선군');
INSERT INTO AREA VALUES(32, 12, '철원군');
INSERT INTO AREA VALUES(32, 13, '춘천시');
INSERT INTO AREA VALUES(32, 14, '태백시');
INSERT INTO AREA VALUES(32, 15, '평창군');
INSERT INTO AREA VALUES(32, 16, '홍천군');
INSERT INTO AREA VALUES(32, 17, '화천군');
INSERT INTO AREA VALUES(32, 18, '횡성군');
INSERT INTO AREA VALUES(33, 0, '충청북도');
INSERT INTO AREA VALUES(33, 1, '괴산군');
INSERT INTO AREA VALUES(33, 2, '단양군');
INSERT INTO AREA VALUES(33, 3, '보은군');
INSERT INTO AREA VALUES(33, 4, '영동군');
INSERT INTO AREA VALUES(33, 5, '옥천군');
INSERT INTO AREA VALUES(33, 6, '음성군');
INSERT INTO AREA VALUES(33, 7, '제천시');
INSERT INTO AREA VALUES(33, 8, '진천군');
INSERT INTO AREA VALUES(33, 10, '청주시');
INSERT INTO AREA VALUES(33, 11, '충주시');
INSERT INTO AREA VALUES(33, 12, '증평군');
INSERT INTO AREA VALUES(34, 0, '충청남도');
INSERT INTO AREA VALUES(34, 1, '공주시');
INSERT INTO AREA VALUES(34, 2, '금산군');
INSERT INTO AREA VALUES(34, 3, '논산시');
INSERT INTO AREA VALUES(34, 4, '당진시');
INSERT INTO AREA VALUES(34, 5, '보령시');
INSERT INTO AREA VALUES(34, 6, '부여군');
INSERT INTO AREA VALUES(34, 7, '서산시');
INSERT INTO AREA VALUES(34, 8, '서천군');
INSERT INTO AREA VALUES(34, 9, '아산시');
INSERT INTO AREA VALUES(34, 11, '예산군');
INSERT INTO AREA VALUES(34, 12, '천안시');
INSERT INTO AREA VALUES(34, 13, '청양군');
INSERT INTO AREA VALUES(34, 14, '태안군');
INSERT INTO AREA VALUES(34, 15, '홍성군');
INSERT INTO AREA VALUES(34, 16, '계룡시');
INSERT INTO AREA VALUES(35, 0, '경상북도');
INSERT INTO AREA VALUES(35, 1, '경산시');
INSERT INTO AREA VALUES(35, 2, '경주시');
INSERT INTO AREA VALUES(35, 3, '고령군');
INSERT INTO AREA VALUES(35, 4, '구미시');
INSERT INTO AREA VALUES(35, 6, '김천시');
INSERT INTO AREA VALUES(35, 7, '문경시');
INSERT INTO AREA VALUES(35, 8, '봉화군');
INSERT INTO AREA VALUES(35, 9, '상주시');
INSERT INTO AREA VALUES(35, 10, '성주군');
INSERT INTO AREA VALUES(35, 11, '안동시');
INSERT INTO AREA VALUES(35, 12, '영덕군');
INSERT INTO AREA VALUES(35, 13, '영양군');
INSERT INTO AREA VALUES(35, 14, '영주시');
INSERT INTO AREA VALUES(35, 15, '영천시');
INSERT INTO AREA VALUES(35, 16, '예천군');
INSERT INTO AREA VALUES(35, 17, '울릉군');
INSERT INTO AREA VALUES(35, 18, '울진군');
INSERT INTO AREA VALUES(35, 19, '의성군');
INSERT INTO AREA VALUES(35, 20, '청도군');
INSERT INTO AREA VALUES(35, 21, '청송군');
INSERT INTO AREA VALUES(35, 22, '칠곡군');
INSERT INTO AREA VALUES(35, 23, '포항시');
INSERT INTO AREA VALUES(36, 0, '경상남도');
INSERT INTO AREA VALUES(36, 1, '거제시');
INSERT INTO AREA VALUES(36, 2, '거창군');
INSERT INTO AREA VALUES(36, 3, '고성군');
INSERT INTO AREA VALUES(36, 4, '김해시');
INSERT INTO AREA VALUES(36, 5, '남해군');
INSERT INTO AREA VALUES(36, 7, '밀양시');
INSERT INTO AREA VALUES(36, 8, '사천시');
INSERT INTO AREA VALUES(36, 9, '산청군');
INSERT INTO AREA VALUES(36, 10, '양산시');
INSERT INTO AREA VALUES(36, 12, '의령군');
INSERT INTO AREA VALUES(36, 13, '진주시');
INSERT INTO AREA VALUES(36, 15, '창녕군');
INSERT INTO AREA VALUES(36, 16, '창원시');
INSERT INTO AREA VALUES(36, 17, '통영시');
INSERT INTO AREA VALUES(36, 18, '하동군');
INSERT INTO AREA VALUES(36, 19, '함안군');
INSERT INTO AREA VALUES(36, 20, '함양군');
INSERT INTO AREA VALUES(36, 21, '합천군');
INSERT INTO AREA VALUES(37, 0, '전북특별자치도');
INSERT INTO AREA VALUES(37, 1, '고창군');
INSERT INTO AREA VALUES(37, 2, '군산시');
INSERT INTO AREA VALUES(37, 3, '김제시');
INSERT INTO AREA VALUES(37, 4, '남원시');
INSERT INTO AREA VALUES(37, 5, '무주군');
INSERT INTO AREA VALUES(37, 6, '부안군');
INSERT INTO AREA VALUES(37, 7, '순창군');
INSERT INTO AREA VALUES(37, 8, '완주군');
INSERT INTO AREA VALUES(37, 9, '익산시');
INSERT INTO AREA VALUES(37, 10, '임실군');
INSERT INTO AREA VALUES(37, 11, '장수군');
INSERT INTO AREA VALUES(37, 12, '전주시');
INSERT INTO AREA VALUES(37, 13, '정읍시');
INSERT INTO AREA VALUES(37, 14, '진안군');
INSERT INTO AREA VALUES(38, 0, '전라남도');
INSERT INTO AREA VALUES(38, 1, '강진군');
INSERT INTO AREA VALUES(38, 2, '고흥군');
INSERT INTO AREA VALUES(38, 3, '곡성군');
INSERT INTO AREA VALUES(38, 4, '광양시');
INSERT INTO AREA VALUES(38, 5, '구례군');
INSERT INTO AREA VALUES(38, 6, '나주시');
INSERT INTO AREA VALUES(38, 7, '담양군');
INSERT INTO AREA VALUES(38, 8, '목포시');
INSERT INTO AREA VALUES(38, 9, '무안군');
INSERT INTO AREA VALUES(38, 10, '보성군');
INSERT INTO AREA VALUES(38, 11, '순천시');
INSERT INTO AREA VALUES(38, 12, '신안군');
INSERT INTO AREA VALUES(38, 13, '여수시');
INSERT INTO AREA VALUES(38, 16, '영광군');
INSERT INTO AREA VALUES(38, 17, '영암군');
INSERT INTO AREA VALUES(38, 18, '완도군');
INSERT INTO AREA VALUES(38, 19, '장성군');
INSERT INTO AREA VALUES(38, 20, '장흥군');
INSERT INTO AREA VALUES(38, 21, '진도군');
INSERT INTO AREA VALUES(38, 22, '함평군');
INSERT INTO AREA VALUES(38, 23, '해남군');
INSERT INTO AREA VALUES(38, 24, '화순군');
INSERT INTO AREA VALUES(39, 0, '제주도');
INSERT INTO AREA VALUES(39, 3, '서귀포시');
INSERT INTO AREA VALUES(39, 4, '제주시');

INSERT INTO BIGCATEGORY VALUES('A01'      ,'자연');
INSERT INTO BIGCATEGORY VALUES('A02'      ,'인문(문화/예술/역사');
INSERT INTO BIGCATEGORY VALUES('B02'      ,'숙박');
INSERT INTO MIDCATEGORY VALUES('A0101'    ,'자연관광지');
INSERT INTO MIDCATEGORY VALUES('A0102'    ,'관광자원');
INSERT INTO MIDCATEGORY VALUES('A0201'    ,'역사관광지');
INSERT INTO MIDCATEGORY VALUES('A0202'    ,'휴양관광지');
INSERT INTO MIDCATEGORY VALUES('A0203'    ,'체험관광지');
INSERT INTO MIDCATEGORY VALUES('A0204'    ,'산업관광지');
INSERT INTO MIDCATEGORY VALUES('A0205'    ,'건축/조형물');
INSERT INTO MIDCATEGORY VALUES('B0201'    ,'숙박시설');
INSERT INTO SMLCATEGORY VALUES('A01010100','국립공원');
INSERT INTO SMLCATEGORY VALUES('A01010200','도립공원');
INSERT INTO SMLCATEGORY VALUES('A01010300','군립공원');
INSERT INTO SMLCATEGORY VALUES('A01010400','산');
INSERT INTO SMLCATEGORY VALUES('A01010500','자연생태관광지');
INSERT INTO SMLCATEGORY VALUES('A01010600','자연휴양림');
INSERT INTO SMLCATEGORY VALUES('A01010700','수목원');
INSERT INTO SMLCATEGORY VALUES('A01010800','폭포');
INSERT INTO SMLCATEGORY VALUES('A01010900','계곡');
INSERT INTO SMLCATEGORY VALUES('A01011000','약수터');
INSERT INTO SMLCATEGORY VALUES('A01011100','해안절경');
INSERT INTO SMLCATEGORY VALUES('A01011200','해수욕장');
INSERT INTO SMLCATEGORY VALUES('A01011300','섬');
INSERT INTO SMLCATEGORY VALUES('A01011400','항구/포구');
INSERT INTO SMLCATEGORY VALUES('A01011600','등대');
INSERT INTO SMLCATEGORY VALUES('A01011700','호수');
INSERT INTO SMLCATEGORY VALUES('A01011800','강');
INSERT INTO SMLCATEGORY VALUES('A01011900','동굴');
INSERT INTO SMLCATEGORY VALUES('A01020100','희귀동.식물');
INSERT INTO SMLCATEGORY VALUES('A01020200','기암괴석');
INSERT INTO SMLCATEGORY VALUES('A02010100','고궁');
INSERT INTO SMLCATEGORY VALUES('A02010200','성');
INSERT INTO SMLCATEGORY VALUES('A02010300','문');
INSERT INTO SMLCATEGORY VALUES('A02010400','고택');
INSERT INTO SMLCATEGORY VALUES('A02010500','생가');
INSERT INTO SMLCATEGORY VALUES('A02010600','민속마을');
INSERT INTO SMLCATEGORY VALUES('A02010700','유적지/사적지');
INSERT INTO SMLCATEGORY VALUES('A02010800','사찰');
INSERT INTO SMLCATEGORY VALUES('A02010900','종교성지');
INSERT INTO SMLCATEGORY VALUES('A02011000','안보관광');
INSERT INTO SMLCATEGORY VALUES('A02020200','관광단지');
INSERT INTO SMLCATEGORY VALUES('A02020300','온천/욕장/스파');
INSERT INTO SMLCATEGORY VALUES('A02020400','이색찜질방');
INSERT INTO SMLCATEGORY VALUES('A02020500','헬스투어');
INSERT INTO SMLCATEGORY VALUES('A02020600','테마공원');
INSERT INTO SMLCATEGORY VALUES('A02020700','공원');
INSERT INTO SMLCATEGORY VALUES('A02020800','유람선/잠수함관광');
INSERT INTO SMLCATEGORY VALUES('A02030100','농.산.어촌 체험');
INSERT INTO SMLCATEGORY VALUES('A02030200','전통체험');
INSERT INTO SMLCATEGORY VALUES('A02030300','산사체험');
INSERT INTO SMLCATEGORY VALUES('A02030400','이색체험');
INSERT INTO SMLCATEGORY VALUES('A02030600','이색거리');
INSERT INTO SMLCATEGORY VALUES('A02040400','발전소');
INSERT INTO SMLCATEGORY VALUES('A02040600','식음료');
INSERT INTO SMLCATEGORY VALUES('A02040800','기타');
INSERT INTO SMLCATEGORY VALUES('A02040900','전자-반도체');
INSERT INTO SMLCATEGORY VALUES('A02041000','자동차');
INSERT INTO SMLCATEGORY VALUES('A02050100','다리/대교');
INSERT INTO SMLCATEGORY VALUES('A02050200','기념탑/기념비/전망대');
INSERT INTO SMLCATEGORY VALUES('A02050300','분수');
INSERT INTO SMLCATEGORY VALUES('A02050400','동상');
INSERT INTO SMLCATEGORY VALUES('A02050500','터널');
INSERT INTO SMLCATEGORY VALUES('A02050600','유명건물');
INSERT INTO SMLCATEGORY VALUES('B02010100','관광호텔');
INSERT INTO SMLCATEGORY VALUES('B02010500','콘도미니엄');
INSERT INTO SMLCATEGORY VALUES('B02010600','유스호스텔');
INSERT INTO SMLCATEGORY VALUES('B02010700','펜션');
INSERT INTO SMLCATEGORY VALUES('B02010900','모텔');
INSERT INTO SMLCATEGORY VALUES('B02011000','민박');
INSERT INTO SMLCATEGORY VALUES('B02011100','게스트하우스');
INSERT INTO SMLCATEGORY VALUES('B02011200','홈스테이');
INSERT INTO SMLCATEGORY VALUES('B02011300','서비스드레지던스');
INSERT INTO SMLCATEGORY VALUES('B02011600','한옥');



INSERT INTO "WEATHER_AREA" (AREA_CODE, AREA_NAME) VALUES ('백령도', '11A00101')
INSERT INTO "WEATHER_AREA" (AREA_CODE, AREA_NAME) VALUES ('서울', '11B10101')
INSERT INTO "WEATHER_AREA" (AREA_CODE, AREA_NAME) VALUES ('과천', '11B10102')
INSERT INTO "WEATHER_AREA" (AREA_CODE, AREA_NAME) VALUES ('광명', '11B10103')
INSERT INTO "WEATHER_AREA" (AREA_CODE, AREA_NAME) VALUES ('강화', '11B20101')
INSERT INTO "WEATHER_AREA" (AREA_CODE, AREA_NAME) VALUES ('김포', '11B20102')
INSERT INTO "WEATHER_AREA" (AREA_CODE, AREA_NAME) VALUES ('인천', '11B20201')
INSERT INTO "WEATHER_AREA" (AREA_CODE, AREA_NAME) VALUES ('시흥', '11B20202')
INSERT INTO "WEATHER_AREA" (AREA_CODE, AREA_NAME) VALUES ('안산', '11B20203')
INSERT INTO "WEATHER_AREA" (AREA_CODE, AREA_NAME) VALUES ('부천', '11B20204')
INSERT INTO "WEATHER_AREA" (AREA_CODE, AREA_NAME) VALUES ('의정부', '11B20301')
INSERT INTO "WEATHER_AREA" (AREA_CODE, AREA_NAME) VALUES ('고양', '11B20302')
INSERT INTO "WEATHER_AREA" (AREA_CODE, AREA_NAME) VALUES ('양주', '11B20304')
INSERT INTO "WEATHER_AREA" (AREA_CODE, AREA_NAME) VALUES ('파주', '11B20305')
INSERT INTO "WEATHER_AREA" (AREA_CODE, AREA_NAME) VALUES ('동두천', '11B20401')
INSERT INTO "WEATHER_AREA" (AREA_CODE, AREA_NAME) VALUES ('연천', '11B20402')
INSERT INTO "WEATHER_AREA" (AREA_CODE, AREA_NAME) VALUES ('포천', '11B20403')
INSERT INTO "WEATHER_AREA" (AREA_CODE, AREA_NAME) VALUES ('가평', '11B20404')
INSERT INTO "WEATHER_AREA" (AREA_CODE, AREA_NAME) VALUES ('구리', '11B20501')
INSERT INTO "WEATHER_AREA" (AREA_CODE, AREA_NAME) VALUES ('남양주', '11B20502')
INSERT INTO "WEATHER_AREA" (AREA_CODE, AREA_NAME) VALUES ('양평', '11B20503')
INSERT INTO "WEATHER_AREA" (AREA_CODE, AREA_NAME) VALUES ('하남', '11B20504')
INSERT INTO "WEATHER_AREA" (AREA_CODE, AREA_NAME) VALUES ('수원', '11B20601')
INSERT INTO "WEATHER_AREA" (AREA_CODE, AREA_NAME) VALUES ('안양', '11B20602')
INSERT INTO "WEATHER_AREA" (AREA_CODE, AREA_NAME) VALUES ('오산', '11B20603')
INSERT INTO "WEATHER_AREA" (AREA_CODE, AREA_NAME) VALUES ('화성', '11B20604')
INSERT INTO "WEATHER_AREA" (AREA_CODE, AREA_NAME) VALUES ('성남', '11B20605')
INSERT INTO "WEATHER_AREA" (AREA_CODE, AREA_NAME) VALUES ('평택', '11B20606')
INSERT INTO "WEATHER_AREA" (AREA_CODE, AREA_NAME) VALUES ('의왕', '11B20609')
INSERT INTO "WEATHER_AREA" (AREA_CODE, AREA_NAME) VALUES ('군포', '11B20610')
INSERT INTO "WEATHER_AREA" (AREA_CODE, AREA_NAME) VALUES ('안성', '11B20611')
INSERT INTO "WEATHER_AREA" (AREA_CODE, AREA_NAME) VALUES ('용인', '11B20612')
INSERT INTO "WEATHER_AREA" (AREA_CODE, AREA_NAME) VALUES ('이천', '11B20701')
INSERT INTO "WEATHER_AREA" (AREA_CODE, AREA_NAME) VALUES ('광주', '11B20702')
INSERT INTO "WEATHER_AREA" (AREA_CODE, AREA_NAME) VALUES ('여주', '11B20703')
INSERT INTO "WEATHER_AREA" (AREA_CODE, AREA_NAME) VALUES ('충주', '11C10101')
INSERT INTO "WEATHER_AREA" (AREA_CODE, AREA_NAME) VALUES ('진천', '11C10102')
INSERT INTO "WEATHER_AREA" (AREA_CODE, AREA_NAME) VALUES ('음성', '11C10103')
INSERT INTO "WEATHER_AREA" (AREA_CODE, AREA_NAME) VALUES ('제천', '11C10201')
INSERT INTO "WEATHER_AREA" (AREA_CODE, AREA_NAME) VALUES ('단양', '11C10202')
INSERT INTO "WEATHER_AREA" (AREA_CODE, AREA_NAME) VALUES ('청주', '11C10301')
INSERT INTO "WEATHER_AREA" (AREA_CODE, AREA_NAME) VALUES ('보은', '11C10302')
INSERT INTO "WEATHER_AREA" (AREA_CODE, AREA_NAME) VALUES ('괴산', '11C10303')
INSERT INTO "WEATHER_AREA" (AREA_CODE, AREA_NAME) VALUES ('증평', '11C10304')
INSERT INTO "WEATHER_AREA" (AREA_CODE, AREA_NAME) VALUES ('추풍령', '11C10401')
INSERT INTO "WEATHER_AREA" (AREA_CODE, AREA_NAME) VALUES ('영동', '11C10402')
INSERT INTO "WEATHER_AREA" (AREA_CODE, AREA_NAME) VALUES ('옥천', '11C10403')
INSERT INTO "WEATHER_AREA" (AREA_CODE, AREA_NAME) VALUES ('서산', '11C20101')
INSERT INTO "WEATHER_AREA" (AREA_CODE, AREA_NAME) VALUES ('태안', '11C20102')
INSERT INTO "WEATHER_AREA" (AREA_CODE, AREA_NAME) VALUES ('당진', '11C20103')
INSERT INTO "WEATHER_AREA" (AREA_CODE, AREA_NAME) VALUES ('홍성', '11C20104')
INSERT INTO "WEATHER_AREA" (AREA_CODE, AREA_NAME) VALUES ('보령', '11C20201')
INSERT INTO "WEATHER_AREA" (AREA_CODE, AREA_NAME) VALUES ('서천', '11C20202')
INSERT INTO "WEATHER_AREA" (AREA_CODE, AREA_NAME) VALUES ('천안', '11C20301')
INSERT INTO "WEATHER_AREA" (AREA_CODE, AREA_NAME) VALUES ('아산', '11C20302')
INSERT INTO "WEATHER_AREA" (AREA_CODE, AREA_NAME) VALUES ('예산', '11C20303')
INSERT INTO "WEATHER_AREA" (AREA_CODE, AREA_NAME) VALUES ('대전', '11C20401')
INSERT INTO "WEATHER_AREA" (AREA_CODE, AREA_NAME) VALUES ('공주', '11C20402')
INSERT INTO "WEATHER_AREA" (AREA_CODE, AREA_NAME) VALUES ('계룡', '11C20403')
INSERT INTO "WEATHER_AREA" (AREA_CODE, AREA_NAME) VALUES ('세종', '11C20404')
INSERT INTO "WEATHER_AREA" (AREA_CODE, AREA_NAME) VALUES ('부여', '11C20501')
INSERT INTO "WEATHER_AREA" (AREA_CODE, AREA_NAME) VALUES ('청양', '11C20502')
INSERT INTO "WEATHER_AREA" (AREA_CODE, AREA_NAME) VALUES ('금산', '11C20601')
INSERT INTO "WEATHER_AREA" (AREA_CODE, AREA_NAME) VALUES ('논산', '11C20602')
INSERT INTO "WEATHER_AREA" (AREA_CODE, AREA_NAME) VALUES ('철원', '11D10101')
INSERT INTO "WEATHER_AREA" (AREA_CODE, AREA_NAME) VALUES ('화천', '11D10102')
INSERT INTO "WEATHER_AREA" (AREA_CODE, AREA_NAME) VALUES ('인제', '11D10201')
INSERT INTO "WEATHER_AREA" (AREA_CODE, AREA_NAME) VALUES ('양구', '11D10202')
INSERT INTO "WEATHER_AREA" (AREA_CODE, AREA_NAME) VALUES ('춘천', '11D10301')
INSERT INTO "WEATHER_AREA" (AREA_CODE, AREA_NAME) VALUES ('홍천', '11D10302')
INSERT INTO "WEATHER_AREA" (AREA_CODE, AREA_NAME) VALUES ('원주', '11D10401')
INSERT INTO "WEATHER_AREA" (AREA_CODE, AREA_NAME) VALUES ('횡성', '11D10402')
INSERT INTO "WEATHER_AREA" (AREA_CODE, AREA_NAME) VALUES ('영월', '11D10501')
INSERT INTO "WEATHER_AREA" (AREA_CODE, AREA_NAME) VALUES ('정선', '11D10502')
INSERT INTO "WEATHER_AREA" (AREA_CODE, AREA_NAME) VALUES ('평창', '11D10503')
INSERT INTO "WEATHER_AREA" (AREA_CODE, AREA_NAME) VALUES ('대관령', '11D20201')
INSERT INTO "WEATHER_AREA" (AREA_CODE, AREA_NAME) VALUES ('태백', '11D20301')
INSERT INTO "WEATHER_AREA" (AREA_CODE, AREA_NAME) VALUES ('속초', '11D20401')
INSERT INTO "WEATHER_AREA" (AREA_CODE, AREA_NAME) VALUES ('고성', '11D20402')
INSERT INTO "WEATHER_AREA" (AREA_CODE, AREA_NAME) VALUES ('양양', '11D20403')
INSERT INTO "WEATHER_AREA" (AREA_CODE, AREA_NAME) VALUES ('강릉', '11D20501')
INSERT INTO "WEATHER_AREA" (AREA_CODE, AREA_NAME) VALUES ('동해', '11D20601')
INSERT INTO "WEATHER_AREA" (AREA_CODE, AREA_NAME) VALUES ('삼척', '11D20602')
INSERT INTO "WEATHER_AREA" (AREA_CODE, AREA_NAME) VALUES ('울릉도', '11E00101')
INSERT INTO "WEATHER_AREA" (AREA_CODE, AREA_NAME) VALUES ('독도', '11E00102')
INSERT INTO "WEATHER_AREA" (AREA_CODE, AREA_NAME) VALUES ('전주', '11F10201')
INSERT INTO "WEATHER_AREA" (AREA_CODE, AREA_NAME) VALUES ('익산', '11F10202')
INSERT INTO "WEATHER_AREA" (AREA_CODE, AREA_NAME) VALUES ('정읍', '11F10203')
INSERT INTO "WEATHER_AREA" (AREA_CODE, AREA_NAME) VALUES ('완주', '11F10204')
INSERT INTO "WEATHER_AREA" (AREA_CODE, AREA_NAME) VALUES ('장수', '11F10301')
INSERT INTO "WEATHER_AREA" (AREA_CODE, AREA_NAME) VALUES ('무주', '11F10302')
INSERT INTO "WEATHER_AREA" (AREA_CODE, AREA_NAME) VALUES ('진안', '11F10303')
INSERT INTO "WEATHER_AREA" (AREA_CODE, AREA_NAME) VALUES ('남원', '11F10401')
INSERT INTO "WEATHER_AREA" (AREA_CODE, AREA_NAME) VALUES ('임실', '11F10402')
INSERT INTO "WEATHER_AREA" (AREA_CODE, AREA_NAME) VALUES ('순창', '11F10403')
INSERT INTO "WEATHER_AREA" (AREA_CODE, AREA_NAME) VALUES ('군산', '21F10501')
INSERT INTO "WEATHER_AREA" (AREA_CODE, AREA_NAME) VALUES ('김제', '21F10502')
INSERT INTO "WEATHER_AREA" (AREA_CODE, AREA_NAME) VALUES ('고창', '21F10601')
INSERT INTO "WEATHER_AREA" (AREA_CODE, AREA_NAME) VALUES ('부안', '21F10602')
INSERT INTO "WEATHER_AREA" (AREA_CODE, AREA_NAME) VALUES ('함평', '21F20101')
INSERT INTO "WEATHER_AREA" (AREA_CODE, AREA_NAME) VALUES ('영광', '21F20102')
INSERT INTO "WEATHER_AREA" (AREA_CODE, AREA_NAME) VALUES ('진도', '21F20201')
INSERT INTO "WEATHER_AREA" (AREA_CODE, AREA_NAME) VALUES ('완도', '11F20301')
INSERT INTO "WEATHER_AREA" (AREA_CODE, AREA_NAME) VALUES ('해남', '11F20302')
INSERT INTO "WEATHER_AREA" (AREA_CODE, AREA_NAME) VALUES ('강진', '11F20303')
INSERT INTO "WEATHER_AREA" (AREA_CODE, AREA_NAME) VALUES ('장흥', '11F20304')
INSERT INTO "WEATHER_AREA" (AREA_CODE, AREA_NAME) VALUES ('여수', '11F20401')
INSERT INTO "WEATHER_AREA" (AREA_CODE, AREA_NAME) VALUES ('광양', '11F20402')
INSERT INTO "WEATHER_AREA" (AREA_CODE, AREA_NAME) VALUES ('고흥', '11F20403')
INSERT INTO "WEATHER_AREA" (AREA_CODE, AREA_NAME) VALUES ('보성', '11F20404')
INSERT INTO "WEATHER_AREA" (AREA_CODE, AREA_NAME) VALUES ('순천시', '11F20405')
INSERT INTO "WEATHER_AREA" (AREA_CODE, AREA_NAME) VALUES ('광주', '11F20501')
INSERT INTO "WEATHER_AREA" (AREA_CODE, AREA_NAME) VALUES ('장성', '11F20502')
INSERT INTO "WEATHER_AREA" (AREA_CODE, AREA_NAME) VALUES ('나주', '11F20503')
INSERT INTO "WEATHER_AREA" (AREA_CODE, AREA_NAME) VALUES ('담양', '11F20504')
INSERT INTO "WEATHER_AREA" (AREA_CODE, AREA_NAME) VALUES ('화순', '11F20505')
INSERT INTO "WEATHER_AREA" (AREA_CODE, AREA_NAME) VALUES ('구례', '11F20601')
INSERT INTO "WEATHER_AREA" (AREA_CODE, AREA_NAME) VALUES ('곡성', '11F20602')
INSERT INTO "WEATHER_AREA" (AREA_CODE, AREA_NAME) VALUES ('순천', '11F20603')
INSERT INTO "WEATHER_AREA" (AREA_CODE, AREA_NAME) VALUES ('흑산도', '11F20701')
INSERT INTO "WEATHER_AREA" (AREA_CODE, AREA_NAME) VALUES ('목포', '21F20801')
INSERT INTO "WEATHER_AREA" (AREA_CODE, AREA_NAME) VALUES ('영암', '21F20802')
INSERT INTO "WEATHER_AREA" (AREA_CODE, AREA_NAME) VALUES ('신안', '21F20803')
INSERT INTO "WEATHER_AREA" (AREA_CODE, AREA_NAME) VALUES ('무안', '21F20804')
INSERT INTO "WEATHER_AREA" (AREA_CODE, AREA_NAME) VALUES ('성산', '11G00101')
INSERT INTO "WEATHER_AREA" (AREA_CODE, AREA_NAME) VALUES ('제주', '11G00201')
INSERT INTO "WEATHER_AREA" (AREA_CODE, AREA_NAME) VALUES ('성판악', '11G00302')
INSERT INTO "WEATHER_AREA" (AREA_CODE, AREA_NAME) VALUES ('서귀포', '11G00401')
INSERT INTO "WEATHER_AREA" (AREA_CODE, AREA_NAME) VALUES ('고산', '11G00501')
INSERT INTO "WEATHER_AREA" (AREA_CODE, AREA_NAME) VALUES ('이어도', '11G00601')
INSERT INTO "WEATHER_AREA" (AREA_CODE, AREA_NAME) VALUES ('추자도', '11G00800')
INSERT INTO "WEATHER_AREA" (AREA_CODE, AREA_NAME) VALUES ('울진', '11H10101')
INSERT INTO "WEATHER_AREA" (AREA_CODE, AREA_NAME) VALUES ('영덕', '11H10102')
INSERT INTO "WEATHER_AREA" (AREA_CODE, AREA_NAME) VALUES ('포항', '11H10201')
INSERT INTO "WEATHER_AREA" (AREA_CODE, AREA_NAME) VALUES ('경주', '11H10202')
INSERT INTO "WEATHER_AREA" (AREA_CODE, AREA_NAME) VALUES ('문경', '11H10301')
INSERT INTO "WEATHER_AREA" (AREA_CODE, AREA_NAME) VALUES ('상주', '11H10302')
INSERT INTO "WEATHER_AREA" (AREA_CODE, AREA_NAME) VALUES ('예천', '11H10303')
INSERT INTO "WEATHER_AREA" (AREA_CODE, AREA_NAME) VALUES ('영주', '11H10401')
INSERT INTO "WEATHER_AREA" (AREA_CODE, AREA_NAME) VALUES ('봉화', '11H10402')
INSERT INTO "WEATHER_AREA" (AREA_CODE, AREA_NAME) VALUES ('영양', '11H10403')
INSERT INTO "WEATHER_AREA" (AREA_CODE, AREA_NAME) VALUES ('안동', '11H10501')
INSERT INTO "WEATHER_AREA" (AREA_CODE, AREA_NAME) VALUES ('의성', '11H10502')
INSERT INTO "WEATHER_AREA" (AREA_CODE, AREA_NAME) VALUES ('청송', '11H10503')
INSERT INTO "WEATHER_AREA" (AREA_CODE, AREA_NAME) VALUES ('김천', '11H10601')
INSERT INTO "WEATHER_AREA" (AREA_CODE, AREA_NAME) VALUES ('구미', '11H10602')
INSERT INTO "WEATHER_AREA" (AREA_CODE, AREA_NAME) VALUES ('군위', '11H10707')
INSERT INTO "WEATHER_AREA" (AREA_CODE, AREA_NAME) VALUES ('고령', '11H10604')
INSERT INTO "WEATHER_AREA" (AREA_CODE, AREA_NAME) VALUES ('성주', '11H10605')
INSERT INTO "WEATHER_AREA" (AREA_CODE, AREA_NAME) VALUES ('대구', '11H10701')
INSERT INTO "WEATHER_AREA" (AREA_CODE, AREA_NAME) VALUES ('영천', '11H10702')
INSERT INTO "WEATHER_AREA" (AREA_CODE, AREA_NAME) VALUES ('경산', '11H10703')
INSERT INTO "WEATHER_AREA" (AREA_CODE, AREA_NAME) VALUES ('청도', '11H10704')
INSERT INTO "WEATHER_AREA" (AREA_CODE, AREA_NAME) VALUES ('칠곡', '11H10705')
INSERT INTO "WEATHER_AREA" (AREA_CODE, AREA_NAME) VALUES ('울산', '11H20101')
INSERT INTO "WEATHER_AREA" (AREA_CODE, AREA_NAME) VALUES ('양산', '11H20102')
INSERT INTO "WEATHER_AREA" (AREA_CODE, AREA_NAME) VALUES ('부산', '11H20201')
INSERT INTO "WEATHER_AREA" (AREA_CODE, AREA_NAME) VALUES ('창원', '11H20301')
INSERT INTO "WEATHER_AREA" (AREA_CODE, AREA_NAME) VALUES ('김해', '11H20304')
INSERT INTO "WEATHER_AREA" (AREA_CODE, AREA_NAME) VALUES ('통영', '11H20401')
INSERT INTO "WEATHER_AREA" (AREA_CODE, AREA_NAME) VALUES ('사천', '11H20402')
INSERT INTO "WEATHER_AREA" (AREA_CODE, AREA_NAME) VALUES ('거제', '11H20403')
INSERT INTO "WEATHER_AREA" (AREA_CODE, AREA_NAME) VALUES ('고성', '11H20404')
INSERT INTO "WEATHER_AREA" (AREA_CODE, AREA_NAME) VALUES ('남해', '11H20405')
INSERT INTO "WEATHER_AREA" (AREA_CODE, AREA_NAME) VALUES ('함양', '11H20501')
INSERT INTO "WEATHER_AREA" (AREA_CODE, AREA_NAME) VALUES ('거창', '11H20502')
INSERT INTO "WEATHER_AREA" (AREA_CODE, AREA_NAME) VALUES ('합천', '11H20503')
INSERT INTO "WEATHER_AREA" (AREA_CODE, AREA_NAME) VALUES ('밀양', '11H20601')
INSERT INTO "WEATHER_AREA" (AREA_CODE, AREA_NAME) VALUES ('의령', '11H20602')
INSERT INTO "WEATHER_AREA" (AREA_CODE, AREA_NAME) VALUES ('함안', '11H20603')
INSERT INTO "WEATHER_AREA" (AREA_CODE, AREA_NAME) VALUES ('창녕', '11H20604')
INSERT INTO "WEATHER_AREA" (AREA_CODE, AREA_NAME) VALUES ('진주', '11H20701')
INSERT INTO "WEATHER_AREA" (AREA_CODE, AREA_NAME) VALUES ('산청', '11H20703')
INSERT INTO "WEATHER_AREA" (AREA_CODE, AREA_NAME) VALUES ('하동', '11H20704')
INSERT INTO "WEATHER_AREA" (AREA_CODE, AREA_NAME) VALUES ('사리원', '11I10001')
INSERT INTO "WEATHER_AREA" (AREA_CODE, AREA_NAME) VALUES ('신계', '11I10002')
INSERT INTO "WEATHER_AREA" (AREA_CODE, AREA_NAME) VALUES ('해주', '11I20001')
INSERT INTO "WEATHER_AREA" (AREA_CODE, AREA_NAME) VALUES ('개성', '11I20002')
INSERT INTO "WEATHER_AREA" (AREA_CODE, AREA_NAME) VALUES ('장연(용연)', '11I20003')
INSERT INTO "WEATHER_AREA" (AREA_CODE, AREA_NAME) VALUES ('신의주', '11J10001')
INSERT INTO "WEATHER_AREA" (AREA_CODE, AREA_NAME) VALUES ('삭주(수풍)', '11J10002')
INSERT INTO "WEATHER_AREA" (AREA_CODE, AREA_NAME) VALUES ('구성', '11J10003')
INSERT INTO "WEATHER_AREA" (AREA_CODE, AREA_NAME) VALUES ('자성(중강)', '11J10004')
INSERT INTO "WEATHER_AREA" (AREA_CODE, AREA_NAME) VALUES ('강계', '11J10005')
INSERT INTO "WEATHER_AREA" (AREA_CODE, AREA_NAME) VALUES ('희천', '11J10006')
INSERT INTO "WEATHER_AREA" (AREA_CODE, AREA_NAME) VALUES ('평양', '11J20001')
INSERT INTO "WEATHER_AREA" (AREA_CODE, AREA_NAME) VALUES ('진남포(남포)', '11J20002')
INSERT INTO "WEATHER_AREA" (AREA_CODE, AREA_NAME) VALUES ('안주', '11J20004')
INSERT INTO "WEATHER_AREA" (AREA_CODE, AREA_NAME) VALUES ('양덕', '11J20005')
INSERT INTO "WEATHER_AREA" (AREA_CODE, AREA_NAME) VALUES ('청진', '11K10001')
INSERT INTO "WEATHER_AREA" (AREA_CODE, AREA_NAME) VALUES ('웅기(선봉)', '11K10002')
INSERT INTO "WEATHER_AREA" (AREA_CODE, AREA_NAME) VALUES ('성진(김책)', '11K10003')
INSERT INTO "WEATHER_AREA" (AREA_CODE, AREA_NAME) VALUES ('무산(삼지연)', '11K10004')
INSERT INTO "WEATHER_AREA" (AREA_CODE, AREA_NAME) VALUES ('함흥', '11K20001')
INSERT INTO "WEATHER_AREA" (AREA_CODE, AREA_NAME) VALUES ('장진', '11K20002')
INSERT INTO "WEATHER_AREA" (AREA_CODE, AREA_NAME) VALUES ('북청(신포)', '11K20003')
INSERT INTO "WEATHER_AREA" (AREA_CODE, AREA_NAME) VALUES ('혜산', '11K20004')
INSERT INTO "WEATHER_AREA" (AREA_CODE, AREA_NAME) VALUES ('풍산', '11K20005')
INSERT INTO "WEATHER_AREA" (AREA_CODE, AREA_NAME) VALUES ('원산', '11L10001')
INSERT INTO "WEATHER_AREA" (AREA_CODE, AREA_NAME) VALUES ('고성(장전)', '11L10002')
INSERT INTO "WEATHER_AREA" (AREA_CODE, AREA_NAME) VALUES ('평강', '11L10003')

