-- 한 줄 주석
/*
    여러 줄 주석
*/

-- 사용자 계정 생성하는 구문
-- [표현법] CREATE USER 계정명 IDENTIFIED BY 비밀번호;
CREATE USER C##KH    IDENTIFIED BY KH   ;
CREATE USER C##STUDY IDENTIFIED BY STUDY;

SELECT * FROM DBA_USERS
 WHERE USERNAME = 'C##STUDY';

-- 생성한 사용자 계정에게 최소한의 권한(데이터관리, 접속) 부여
GRANT RESOURCE, CONNECT TO C##KH;
GRANT RESOURCE, CONNECT TO C##STUDY;

-- 테이블이 저장되는 공간인 테이블스페이스 할당
ALTER USER C##KH    DEFAULT TABLESPACE SYSTEM QUOTA UNLIMITED ON SYSTEM;
ALTER USER C##STUDY DEFAULT TABLESPACE SYSTEM QUOTA UNLIMITED ON SYSTEM;
