-- 사용자 계정 생성하는 구문
-- [표현법] CREATE USER 계정명 IDENTIFIED BY 비밀번호;
CREATE USER C##STUDY IDENTIFIED BY STUDY;

SELECT * FROM DBA_USERS;

-- 생성한 사용자 계정에게 최소한의 권한(데이터관리, 접속) 부여
GRANT RESOURCE, CONNECT TO C##STUDY;

-- 테이블이 저장되는 공간인 테이블스페이스 할당
ALTER USER C##STUDY DEFAULT TABLESPACE SYSTEM QUOTA UNLIMITED ON SYSTEM;



SELECT ', ' || COLUMN_NAME || ' AS "' || COMMENTS || '"'FROM ALL_COL_COMMENTS  WHERE TABLE_NAME = 'EMPLOYEE';

SELECT OWNER ,
       TABLE_NAME ,
       COLUMN_NAME ,
       COMMENTS ,
       ORIGIN_CON_ID
  FROM ALL_COL_COMMENTS
 WHERE TABLE_NAME = 'EMPLOYEE';

SELECT * FROM ALL_TAB_COMMENTS
 WHERE OWNER = 'C##STUDY'
;
SELECT * FROM ALL_TAB_COLUMNS
 WHERE OWNER = 'C##STUDY'
;
SELECT * FROM ALL_TAB_COLUMNS;

SELECT * FROM ALL_TAB_COLUMNS;
SELECT * FROM ALL_TAB_COLUMNS WHERE TABLE_NAME = 'TB_DEPARTMENT';
SELECT * FROM ALL_TAB_COLUMNS WHERE TABLE_NAME = 'TB_CLASS';
SELECT * FROM ALL_TAB_COLUMNS WHERE TABLE_NAME = 'TB_PROFESSOR';
SELECT * FROM ALL_TAB_COLUMNS WHERE TABLE_NAME = 'TB_CLASS_PROFESSOR';
SELECT * FROM ALL_TAB_COLUMNS WHERE TABLE_NAME = 'TB_STUDENT';
SELECT * FROM ALL_TAB_COLUMNS WHERE TABLE_NAME = 'TB_GRADE';

SELECT ', ' || COLUMN_NAME || ' AS "' || COMMENTS || '"'FROM ALL_COL_COMMENTS  WHERE TABLE_NAME = 'TABLE_NAME';
SELECT ', ' || COLUMN_NAME || ' AS "' || COMMENTS || '"'FROM ALL_COL_COMMENTS  WHERE TABLE_NAME = 'TB_DEPARTMENT';
SELECT ', ' || COLUMN_NAME || ' AS "' || COMMENTS || '"'FROM ALL_COL_COMMENTS  WHERE TABLE_NAME = 'TB_CLASS';
SELECT ', ' || COLUMN_NAME || ' AS "' || COMMENTS || '"'FROM ALL_COL_COMMENTS  WHERE TABLE_NAME = 'TB_PROFESSOR';
SELECT ', ' || COLUMN_NAME || ' AS "' || COMMENTS || '"'FROM ALL_COL_COMMENTS  WHERE TABLE_NAME = 'TB_CLASS_PROFESSOR';
SELECT ', ' || COLUMN_NAME || ' AS "' || COMMENTS || '"'FROM ALL_COL_COMMENTS  WHERE TABLE_NAME = 'TB_STUDENT';
SELECT ', ' || COLUMN_NAME || ' AS "' || COMMENTS || '"'FROM ALL_COL_COMMENTS  WHERE TABLE_NAME = 'TB_GRADE';
/*
SELECT
     , DEPARTMENT_NO    AS "학과 번호"
     , DEPARTMENT_NAME  AS "학과 이름"
     , CATEGORY         AS "계열"
     , OPEN_YN          AS "개설 여부"
     , CAPACITY         AS "정원"
  FROM TB_DEPARTMENT AS "학과"
;
SELECT
     , CLASS_NO              AS "과목 번호"
     , DEPARTMENT_NO         AS "학과 번호"
     , PREATTENDING_CLASS_NO AS "선수 과목 번호"
     , CLASS_NAME            AS "과목 이름"
     , CLASS_TYPE            AS "과목 구분"
  FROM TB_CLASS           AS "과목"
;
SELECT
     , PROFESSOR_NO          AS "교수 번호"
     , PROFESSOR_NAME        AS "교수 이름"
     , PROFESSOR_SSN         AS "교수 주민번호"
     , PROFESSOR_ADDRESS     AS "교수 주소"
     , DEPARTMENT_NO         AS "학과 번호"
  FROM TB_PROFESSOR       AS "교수"
;
SELECT
     , CLASS_NO               AS "과목 번호"
     , PROFESSOR_NO           AS "교수 번호"
  FROM TB_CLASS_PROFESSOR  AS "과목 교수"
;
SELECT
     , STUDENT_NO         AS "학생 번호"
     , DEPARTMENT_NO      AS "학과 번호"
     , STUDENT_NAME       AS "학생 이름"
     , STUDENT_SSN        AS "학생 주민번호"
     , STUDENT_ADDRESS    AS "학생 주소"
     , ENTRANCE_DATE      AS "입학 년도"
     , ABSENCE_YN         AS "휴학 여부"
     , COACH_PROFESSOR_NO AS "지도 교수 번호"
  FROM TB_STUDENT      AS "학생"
;
SELECT
     , TERM_NO            AS "학기 번호"
     , STUDENT_NO         AS "학생 번호"
     , CLASS_NO           AS "과목 번호"
     , POINT              AS "학점"
  FROM TB_GRADE        AS "성적"
;
*/