-- PK로 사용할
-- 각 영역 시퀀스 번호 생성
-- 1) 영화: MV
CREATE SEQUENCE SEQ_MV_NO
MAXVALUE 9999;
-- 2) 예매: TK
CREATE SEQUENCE SEQ_TK_NO
MAXVALUE 9999;
-- 3) 극장: CN
CREATE SEQUENCE SEQ_CN_NO
MAXVALUE 9999;
-- 4) 문의: QT
CREATE SEQUENCE SEQ_QT_NO
MAXVALUE 9999;
-- 5) 멤버: MEM
CREATE SEQUENCE SEQ_MEM_NO
MAXVALUE 9999;

SELECT * FROM USER_SEQUENCES;
